/* Autogenerated by png2wx.pl on Wed Sep 29 16:33:27 2010 */
#ifndef _IMG_TOOL_MVERTEX_H_
#define _IMG_TOOL_MVERTEX_H_ 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_image_mvertex(void);
extern void uninitialize_image_mvertex(void);

extern wxBitmap *_img_tool_mvertex;

#endif /* _IMG_TOOL_MVERTEX_H_ */
