coverage:
  precision: 2
  round: nearest
  range: "20...100"
  status:
    project: off
    patch: off
ignore:
  - "/usr/.*"
  - "test/.*"
  - ".*/test/.*"
  - "test/src_test/.*"
  - ".*/test/src_test/.*"
  - "/home/travis/build/terranum-ch/ToolMap/test/src_test/*"
  - ".*/gui/.*"
  - ".*/lib/.*"
  - ".*/include/.*"
