##
## OPTIONS FOR wxTreeMultiCtrl
##

OPTION(USE_CHECKBOXVIEW "Enable checkbox view functionality" OFF)

IF (LINUX)
    ADD_DEFINITIONS(-DLINUX=1)
ENDIF (LINUX)

IF (USE_CHECKBOXVIEW)
    ADD_DEFINITIONS(-DCHECKBOXVIEW=1 ${wxWidgets_DEFINITIONS})
ELSE (USE_CHECKBOXVIEW)
    ADD_DEFINITIONS(-DCHECKBOXVIEW=0 ${wxWidgets_DEFINITIONS})
ENDIF (USE_CHECKBOXVIEW)
