/////////////////////////////////////////////////////////////////////////////
// Name:        addfield.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Mon 20 Aug 15:04:17 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 20 Aug 15:04:17 2007

#ifndef _ADDFIELD_H_
#define _ADDFIELD_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/spinctrl.h"
#include "wx/notebook.h"
#include "wx/grid.h"
#include "wx/tglbtn.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_WXDIALOG 10011
#define ID_TEXTCTRL4 10012
#define ID_CHOICE2 10013
#define ID_SPINCTRL1 10015
#define ID_SPINCTRL2 10014
#define ID_TEXTCTRL5 10016
#define ID_CHECKBOX4 10118
#define ID_CHECKBOX2 10050
#define ID_NOTEBOOK 10000
#define ID_PANEL16 10114
#define ID_GRID2 10117
#define ID_CHOICE15 10228
#define ID_TOGGLEBUTTON1 10217
#define ID_TOGGLEBUTTON2 10215
#define ID_TOGGLEBUTTON3 10216
#define ID_TOGGLEBUTTON4 10218
#define ID_PANEL17 10017
#define ID_TEXTCTRL12 10018
#define ID_TEXTCTRL13 10115
#define ID_TEXTCTRL14 10116
#define SYMBOL_WXDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_WXDIALOG_TITLE _("Attribute field definition")
#define SYMBOL_WXDIALOG_IDNAME ID_WXDIALOG
#define SYMBOL_WXDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_WXDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * wxDialog class declaration
 */

class wxDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( wxDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxDialog();
    wxDialog( wxWindow* parent, wxWindowID id = SYMBOL_WXDIALOG_IDNAME, const wxString& caption = SYMBOL_WXDIALOG_TITLE, const wxPoint& pos = SYMBOL_WXDIALOG_POSITION, const wxSize& size = SYMBOL_WXDIALOG_SIZE, long style = SYMBOL_WXDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXDIALOG_IDNAME, const wxString& caption = SYMBOL_WXDIALOG_TITLE, const wxPoint& pos = SYMBOL_WXDIALOG_POSITION, const wxSize& size = SYMBOL_WXDIALOG_SIZE, long style = SYMBOL_WXDIALOG_STYLE );

    /// Destructor
    ~wxDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxDialog event handler declarations

////@end wxDialog event handler declarations

////@begin wxDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxDialog member variables
////@end wxDialog member variables
};

#endif
    // _ADDFIELD_H_
