/////////////////////////////////////////////////////////////////////////////
// Name:        addspatiallayer.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Tue 21 Aug 14:06:29 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Tue 21 Aug 14:06:29 2007

#ifndef _ADDSPATIALLAYER_H_
#define _ADDSPATIALLAYER_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/notebook.h"
#include "wx/listctrl.h"
#include "wx/tglbtn.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_WXDIALOG 10007
#define ID_CHOICE 10000
#define ID_TEXTCTRL 10001
#define ID_NOTEBOOK 10002
#define ID_PANEL 10003
#define ID_LISTCTRL2 10009
#define ID_TOGGLEBUTTON7 10010
#define ID_TOGGLEBUTTON8 10225
#define ID_TOGGLEBUTTON28 10251
#define ID_PANEL1 10008
#define ID_LISTCTRL 10004
#define ID_TOGGLEBUTTON 10005
#define ID_TOGGLEBUTTON1 10006
#define SYMBOL_WXDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_WXDIALOG_TITLE _("Thematic layer definition")
#define SYMBOL_WXDIALOG_IDNAME ID_WXDIALOG
#define SYMBOL_WXDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_WXDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * wxDialog class declaration
 */

class wxDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( wxDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxDialog();
    wxDialog( wxWindow* parent, wxWindowID id = SYMBOL_WXDIALOG_IDNAME, const wxString& caption = SYMBOL_WXDIALOG_TITLE, const wxPoint& pos = SYMBOL_WXDIALOG_POSITION, const wxSize& size = SYMBOL_WXDIALOG_SIZE, long style = SYMBOL_WXDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXDIALOG_IDNAME, const wxString& caption = SYMBOL_WXDIALOG_TITLE, const wxPoint& pos = SYMBOL_WXDIALOG_POSITION, const wxSize& size = SYMBOL_WXDIALOG_SIZE, long style = SYMBOL_WXDIALOG_STYLE );

    /// Destructor
    ~wxDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxDialog event handler declarations

////@end wxDialog event handler declarations

////@begin wxDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxDialog member variables
////@end wxDialog member variables
};

#endif
    // _ADDSPATIALLAYER_H_
