/////////////////////////////////////////////////////////////////////////////
// Name:        addspatiallayer.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Tue 21 Aug 14:06:29 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Tue 21 Aug 14:06:29 2007

#ifndef _ADDSPATIALLAYER_H_
#define _ADDSPATIALLAYER_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/notebook.h"
#include "wx/listctrl.h"
#include "wx/tglbtn.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class ProjectDefLayersObjectList;
class ProjectDefLayersFieldsList;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DLGPDL 10007
#define ID_DLGPDL_LAYER_TYPE 10000
#define ID_DLGPDL_LAYER_NAME 10001
#define ID_NOTEBOOK 10002
#define ID_DLGPDL_PANEL_OBJ 10003
#define ID_DLGPDL_OBJ_LIST 10009
#define ID_DLGPDL_OBJECT_ADD 10010
#define ID_DLGPDL_OBJECT_REMOVE 10225
#define ID_DLGPDL_OBJECT_IMPORT 10251
#define ID_DLGPDL_PANEL_FIELDS 10008
#define ID_DLGPDL_FIELDS_LIST 10220
#define ID_DLGPDL_FIELD_ADD 10005
#define ID_DLGPDL_FIELD_REMOVE 10006
#define SYMBOL_PROJECTDEFLAYERSDLG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_PROJECTDEFLAYERSDLG_TITLE _("Thematic layer definition")
#define SYMBOL_PROJECTDEFLAYERSDLG_IDNAME ID_DLGPDL
#define SYMBOL_PROJECTDEFLAYERSDLG_SIZE wxSize(400, 300)
#define SYMBOL_PROJECTDEFLAYERSDLG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ProjectDefLayersDlg class declaration
 */

class ProjectDefLayersDlg: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( ProjectDefLayersDlg )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ProjectDefLayersDlg();
    ProjectDefLayersDlg( wxWindow* parent, wxWindowID id = SYMBOL_PROJECTDEFLAYERSDLG_IDNAME, const wxString& caption = SYMBOL_PROJECTDEFLAYERSDLG_TITLE, const wxPoint& pos = SYMBOL_PROJECTDEFLAYERSDLG_POSITION, const wxSize& size = SYMBOL_PROJECTDEFLAYERSDLG_SIZE, long style = SYMBOL_PROJECTDEFLAYERSDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_PROJECTDEFLAYERSDLG_IDNAME, const wxString& caption = SYMBOL_PROJECTDEFLAYERSDLG_TITLE, const wxPoint& pos = SYMBOL_PROJECTDEFLAYERSDLG_POSITION, const wxSize& size = SYMBOL_PROJECTDEFLAYERSDLG_SIZE, long style = SYMBOL_PROJECTDEFLAYERSDLG_STYLE );

    /// Destructor
    ~ProjectDefLayersDlg();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin ProjectDefLayersDlg event handler declarations

////@end ProjectDefLayersDlg event handler declarations

////@begin ProjectDefLayersDlg member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ProjectDefLayersDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ProjectDefLayersDlg member variables
    wxChoice* m_DlgPDL_Layer_Type;
    wxTextCtrl* m_DlgPDL_Layer_Name;
    wxPanel* m_DlgPDL_Panel_Obj;
    ProjectDefLayersObjectList* m_DlgPDL_Object_List;
    wxPanel* m_DlgPDL_Panel_Fields;
    ProjectDefLayersFieldsList* m_DlgPDL_Fields_List;
////@end ProjectDefLayersDlg member variables
};

#endif
    // _ADDSPATIALLAYER_H_
