/////////////////////////////////////////////////////////////////////////////
// Name:        dlg_attribution.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Mon  6 Aug 15:19:35 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 6 Aug 15:19:35 2007

#ifndef _DLG_ATTRIBUTION_H_
#define _DLG_ATTRIBUTION_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/notebook.h"
#include "wx/grid.h"
#include "wx/tglbtn.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DLG_ATTRIBUTION 10025
#define ID_NOTEBOOK1 10026
#define ID_PANEL1 10027
#define ID_GRID1 10030
#define ID_CHOICE16 10234
#define ID_CHOICE17 10235
#define ID_TOGGLEBUTTON9 10031
#define ID_TOGGLEBUTTON11 10232
#define ID_TOGGLEBUTTON12 10233
#define ID_TOGGLEBUTTON10 10032
#define ID_PANEL2 10028
#define ID_PANEL3 10029
#define SYMBOL_DLG_ATTRIBUTION_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_DLG_ATTRIBUTION_TITLE _("Objects definition")
#define SYMBOL_DLG_ATTRIBUTION_IDNAME ID_DLG_ATTRIBUTION
#define SYMBOL_DLG_ATTRIBUTION_SIZE wxDefaultSize
#define SYMBOL_DLG_ATTRIBUTION_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * dlg_attribution class declaration
 */

class dlg_attribution: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( dlg_attribution )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    dlg_attribution();
    dlg_attribution( wxWindow* parent, wxWindowID id = SYMBOL_DLG_ATTRIBUTION_IDNAME, const wxString& caption = SYMBOL_DLG_ATTRIBUTION_TITLE, const wxPoint& pos = SYMBOL_DLG_ATTRIBUTION_POSITION, const wxSize& size = SYMBOL_DLG_ATTRIBUTION_SIZE, long style = SYMBOL_DLG_ATTRIBUTION_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_DLG_ATTRIBUTION_IDNAME, const wxString& caption = SYMBOL_DLG_ATTRIBUTION_TITLE, const wxPoint& pos = SYMBOL_DLG_ATTRIBUTION_POSITION, const wxSize& size = SYMBOL_DLG_ATTRIBUTION_SIZE, long style = SYMBOL_DLG_ATTRIBUTION_STYLE );

    /// Destructor
    ~dlg_attribution();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin dlg_attribution event handler declarations

////@end dlg_attribution event handler declarations

////@begin dlg_attribution member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end dlg_attribution member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin dlg_attribution member variables
////@end dlg_attribution member variables
};

#endif
    // _DLG_ATTRIBUTION_H_
