/////////////////////////////////////////////////////////////////////////////
// Name:        editvertexposition.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Mon  8 Oct 11:06:20 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 8 Oct 11:06:20 2007

#ifndef _EDITVERTEXPOSITION_H_
#define _EDITVERTEXPOSITION_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/grid.h"
#include "wx/tglbtn.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_EDITVERTEXPOSITION 10212
#define ID_GRID3 10213
#define ID_TOGGLEBUTTON26 10249
#define ID_TOGGLEBUTTON27 10250
#define SYMBOL_EDITVERTEXPOSITION_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_EDITVERTEXPOSITION_TITLE _("Edit vertex position")
#define SYMBOL_EDITVERTEXPOSITION_IDNAME ID_EDITVERTEXPOSITION
#define SYMBOL_EDITVERTEXPOSITION_SIZE wxSize(400, 300)
#define SYMBOL_EDITVERTEXPOSITION_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * Editvertexposition class declaration
 */

class Editvertexposition: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( Editvertexposition )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    Editvertexposition();
    Editvertexposition( wxWindow* parent, wxWindowID id = SYMBOL_EDITVERTEXPOSITION_IDNAME, const wxString& caption = SYMBOL_EDITVERTEXPOSITION_TITLE, const wxPoint& pos = SYMBOL_EDITVERTEXPOSITION_POSITION, const wxSize& size = SYMBOL_EDITVERTEXPOSITION_SIZE, long style = SYMBOL_EDITVERTEXPOSITION_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_EDITVERTEXPOSITION_IDNAME, const wxString& caption = SYMBOL_EDITVERTEXPOSITION_TITLE, const wxPoint& pos = SYMBOL_EDITVERTEXPOSITION_POSITION, const wxSize& size = SYMBOL_EDITVERTEXPOSITION_SIZE, long style = SYMBOL_EDITVERTEXPOSITION_STYLE );

    /// Destructor
    ~Editvertexposition();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin Editvertexposition event handler declarations

////@end Editvertexposition event handler declarations

////@begin Editvertexposition member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end Editvertexposition member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin Editvertexposition member variables
////@end Editvertexposition member variables
};

#endif
    // _EDITVERTEXPOSITION_H_
