/////////////////////////////////////////////////////////////////////////////
// Name:        newprojectfromexisting.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Wed 29 Aug 08:42:46 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Wed 29 Aug 08:42:46 2007

#ifndef _NEWPROJECTFROMEXISTING_H_
#define _NEWPROJECTFROMEXISTING_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/statline.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_NEWPROJECTFROMEXISTING 10036
#define ID_TEXTCTRL15 10149
#define ID_DLGNPE_NEW_PRJ_PATH_BTN 10150
#define ID_TEXTCTRL16 10151
#define ID_STATICLINE1 10152
#define ID_TEXTCTRL17 10153
#define ID_DLGNPE_OLD_PRJ_PATH_BTN 10154
#define ID_DLGNPE_RADIO_OPTIONS 10155
#define SYMBOL_PROJECTNEWEXISTDLG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_PROJECTNEWEXISTDLG_TITLE _("New project from existing")
#define SYMBOL_PROJECTNEWEXISTDLG_IDNAME ID_NEWPROJECTFROMEXISTING
#define SYMBOL_PROJECTNEWEXISTDLG_SIZE wxSize(400, 300)
#define SYMBOL_PROJECTNEWEXISTDLG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ProjectNewExistDLG class declaration
 */

class ProjectNewExistDLG: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( ProjectNewExistDLG )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ProjectNewExistDLG();
    ProjectNewExistDLG( wxWindow* parent, wxWindowID id = SYMBOL_PROJECTNEWEXISTDLG_IDNAME, const wxString& caption = SYMBOL_PROJECTNEWEXISTDLG_TITLE, const wxPoint& pos = SYMBOL_PROJECTNEWEXISTDLG_POSITION, const wxSize& size = SYMBOL_PROJECTNEWEXISTDLG_SIZE, long style = SYMBOL_PROJECTNEWEXISTDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_PROJECTNEWEXISTDLG_IDNAME, const wxString& caption = SYMBOL_PROJECTNEWEXISTDLG_TITLE, const wxPoint& pos = SYMBOL_PROJECTNEWEXISTDLG_POSITION, const wxSize& size = SYMBOL_PROJECTNEWEXISTDLG_SIZE, long style = SYMBOL_PROJECTNEWEXISTDLG_STYLE );

    /// Destructor
    ~ProjectNewExistDLG();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin ProjectNewExistDLG event handler declarations

////@end ProjectNewExistDLG event handler declarations

////@begin ProjectNewExistDLG member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ProjectNewExistDLG member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ProjectNewExistDLG member variables
    wxTextCtrl* m_DlgPNE_New_Prj_Path;
    wxTextCtrl* m_DlgPNE_New_Prj_Name;
    wxTextCtrl* m_DlgPNE_Old_Prj_Path;
    wxRadioBox* m_DlgPNE_Options;
    wxButton* m_DlgPNE_Btn_OK;
////@end ProjectNewExistDLG member variables
};

#endif
    // _NEWPROJECTFROMEXISTING_H_
