/////////////////////////////////////////////////////////////////////////////
// Name:        newproject.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Mon  6 Aug 17:03:00 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 6 Aug 17:03:00 2007

#ifndef _NEWPROJECT_H_
#define _NEWPROJECT_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/listctrl.h"
#include "wx/tglbtn.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class ListParam;
class wxToggleButton;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DLGPD 10000
#define ID_DLGPD_PROJ_PATH 10001
#define ID_DLGPD_PROJ_NAME 10003
#define ID_DLGPD_PROJ_UNIT 10156
#define ID_DLGPD_PROJ_PROJECTION 10119
#define ID_DLGPD_SPAT_MODEL_LIST 10004
#define ID_DLGPD_SPAT_MDL_ADD 10219
#define ID_DLJPD_SPAT_MDL_DEL 10006
#define SYMBOL_PROJECTDEFDLG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_PROJECTDEFDLG_TITLE _("Project Definition")
#define SYMBOL_PROJECTDEFDLG_IDNAME ID_DLGPD
#define SYMBOL_PROJECTDEFDLG_SIZE wxSize(400, 300)
#define SYMBOL_PROJECTDEFDLG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ProjectDefDLG class declaration
 */

class ProjectDefDLG: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( ProjectDefDLG )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ProjectDefDLG();
    ProjectDefDLG( wxWindow* parent, wxWindowID id = SYMBOL_PROJECTDEFDLG_IDNAME, const wxString& caption = SYMBOL_PROJECTDEFDLG_TITLE, const wxPoint& pos = SYMBOL_PROJECTDEFDLG_POSITION, const wxSize& size = SYMBOL_PROJECTDEFDLG_SIZE, long style = SYMBOL_PROJECTDEFDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_PROJECTDEFDLG_IDNAME, const wxString& caption = SYMBOL_PROJECTDEFDLG_TITLE, const wxPoint& pos = SYMBOL_PROJECTDEFDLG_POSITION, const wxSize& size = SYMBOL_PROJECTDEFDLG_SIZE, long style = SYMBOL_PROJECTDEFDLG_STYLE );

    /// Destructor
    ~ProjectDefDLG();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin ProjectDefDLG event handler declarations

////@end ProjectDefDLG event handler declarations

////@begin ProjectDefDLG member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ProjectDefDLG member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ProjectDefDLG member variables
    wxTextCtrl* m_DlgPD_Proj_Path;
    wxTextCtrl* m_DlgPd_Proj_Name;
    wxChoice* m_DlgPd_Proj_Unit;
    wxChoice* m_DlgPd_Proj_Projection;
    ListParam* m_DlgPd_Stat_Model_List;
    wxToggleButton* m_DlgPd_Spat_Mdl_Add;
    wxToggleButton* m_DljPd_Spat_Mdl_Del;
////@end ProjectDefDLG member variables
};

#endif
    // _NEWPROJECT_H_
