/////////////////////////////////////////////////////////////////////////////
// Name:        projectproperties.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Mon 27 Aug 15:48:36 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 27 Aug 15:48:36 2007

#ifndef _PROJECTPROPERTIES_H_
#define _PROJECTPROPERTIES_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/notebook.h"
#include "wx/tglbtn.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_PROJECTPROPERTIES 10132
#define ID_NOTEBOOK7 10141
#define ID_PANEL18 10142
#define ID_CHOICE 10000
#define ID_TEXTCTRL 10001
#define ID_BUTTON 10002
#define ID_TEXTCTRL1 10003
#define ID_BUTTON1 10004
#define ID_PANEL19 10133
#define ID_LISTBOX2 10134
#define ID_TOGGLEBUTTON19 10239
#define ID_TOGGLEBUTTON20 10240
#define ID_CHOICE19 10135
#define SYMBOL_PROJECTPROPERTIES_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_PROJECTPROPERTIES_TITLE _("Project settings")
#define SYMBOL_PROJECTPROPERTIES_IDNAME ID_PROJECTPROPERTIES
#define SYMBOL_PROJECTPROPERTIES_SIZE wxSize(400, 300)
#define SYMBOL_PROJECTPROPERTIES_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * Projectproperties class declaration
 */

class Projectproperties: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( Projectproperties )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    Projectproperties();
    Projectproperties( wxWindow* parent, wxWindowID id = SYMBOL_PROJECTPROPERTIES_IDNAME, const wxString& caption = SYMBOL_PROJECTPROPERTIES_TITLE, const wxPoint& pos = SYMBOL_PROJECTPROPERTIES_POSITION, const wxSize& size = SYMBOL_PROJECTPROPERTIES_SIZE, long style = SYMBOL_PROJECTPROPERTIES_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_PROJECTPROPERTIES_IDNAME, const wxString& caption = SYMBOL_PROJECTPROPERTIES_TITLE, const wxPoint& pos = SYMBOL_PROJECTPROPERTIES_POSITION, const wxSize& size = SYMBOL_PROJECTPROPERTIES_SIZE, long style = SYMBOL_PROJECTPROPERTIES_STYLE );

    /// Destructor
    ~Projectproperties();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin Projectproperties event handler declarations

////@end Projectproperties event handler declarations

////@begin Projectproperties member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end Projectproperties member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin Projectproperties member variables
////@end Projectproperties member variables
};

#endif
    // _PROJECTPROPERTIES_H_
