/////////////////////////////////////////////////////////////////////////////
// Name:        querieseditor.cpp
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Tue 21 Aug 12:23:05 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Tue 21 Aug 12:23:05 2007

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "querieseditor.h"

////@begin XPM images
////@end XPM images


/*!
 * Queries_PANEL type definition
 */

IMPLEMENT_DYNAMIC_CLASS( Queries_PANEL, ManagedAuiWnd )


/*!
 * Queries_PANEL event table definition
 */

BEGIN_EVENT_TABLE( Queries_PANEL, ManagedAuiWnd )

////@begin Queries_PANEL event table entries
////@end Queries_PANEL event table entries

END_EVENT_TABLE()


/*!
 * Queries_PANEL constructors
 */

Queries_PANEL::Queries_PANEL()
{
    Init();
}

Queries_PANEL::Queries_PANEL( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}


/*!
 * QueriesEditor creator
 */

bool Queries_PANEL::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin Queries_PANEL creation
    SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
    ManagedAuiWnd::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end Queries_PANEL creation
    return true;
}


/*!
 * Queries_PANEL destructor
 */

Queries_PANEL::~Queries_PANEL()
{
////@begin Queries_PANEL destruction
////@end Queries_PANEL destruction
}


/*!
 * Member initialisation
 */

void Queries_PANEL::Init()
{
////@begin Queries_PANEL member initialisation
////@end Queries_PANEL member initialisation
}


/*!
 * Control creation for QueriesEditor
 */

void Queries_PANEL::CreateControls()
{    
////@begin Queries_PANEL content construction
    // Generated by DialogBlocks, Sat 8 Nov 18:05:18 2008 (Personal Edition)

    Queries_PANEL* itemManagedAuiWnd1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemManagedAuiWnd1->SetSizer(itemBoxSizer2);

    wxStaticBox* itemStaticBoxSizer3Static = new wxStaticBox(itemManagedAuiWnd1, wxID_ANY, _("Define your queries"));
    wxStaticBoxSizer* itemStaticBoxSizer3 = new wxStaticBoxSizer(itemStaticBoxSizer3Static, wxVERTICAL);
    itemBoxSizer2->Add(itemStaticBoxSizer3, 1, wxGROW|wxALL, 5);

    wxListCtrl* itemListCtrl4 = new wxListCtrl( itemManagedAuiWnd1, ID_LISTCTRL4, wxDefaultPosition, wxSize(100, 100), wxLC_REPORT );
    itemStaticBoxSizer3->Add(itemListCtrl4, 1, wxGROW|wxTOP|wxBOTTOM, 5);

    wxBoxSizer* itemBoxSizer5 = new wxBoxSizer(wxHORIZONTAL);
    itemStaticBoxSizer3->Add(itemBoxSizer5, 0, wxALIGN_LEFT|wxLEFT|wxRIGHT, 5);

    wxToggleButton* itemToggleButton6 = new wxToggleButton( itemManagedAuiWnd1, ID_TOGGLEBUTTON13, _("+"), wxDefaultPosition, wxSize(40, -1), 0 );
    itemToggleButton6->SetValue(false);
    itemBoxSizer5->Add(itemToggleButton6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxToggleButton* itemToggleButton7 = new wxToggleButton( itemManagedAuiWnd1, ID_TOGGLEBUTTON14, _("-"), wxDefaultPosition, wxSize(40, -1), 0 );
    itemToggleButton7->SetValue(false);
    itemBoxSizer5->Add(itemToggleButton7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxToggleButton* itemToggleButton8 = new wxToggleButton( itemManagedAuiWnd1, ID_TOGGLEBUTTON15, _("Run selected"), wxDefaultPosition, wxDefaultSize, 0 );
    itemToggleButton8->SetValue(false);
    itemBoxSizer5->Add(itemToggleButton8, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxBoxSizer* itemBoxSizer9 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer9, 0, wxALIGN_RIGHT|wxALL, 5);

    wxButton* itemButton10 = new wxButton( itemManagedAuiWnd1, ID_BUTTON, _("Clear selection"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer9->Add(itemButton10, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton11 = new wxButton( itemManagedAuiWnd1, wxID_CLOSE, _("&Close"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer9->Add(itemButton11, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton12 = new wxButton( itemManagedAuiWnd1, wxID_SAVE, _("&Save queries"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer9->Add(itemButton12, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStatusBar* itemStatusBar13 = new wxStatusBar( itemManagedAuiWnd1, ID_STATUSBAR1, wxST_SIZEGRIP|wxNO_BORDER );
    itemStatusBar13->SetFieldsCount(2);
    itemStatusBar13->SetStatusText(_("Query passed OK"), 0);
    itemStatusBar13->SetStatusText(_("10 Queries"), 1);
    int itemStatusBar13Widths[2];
    itemStatusBar13Widths[0] = -2;
    itemStatusBar13Widths[1] = -1;
    itemStatusBar13->SetStatusWidths(2, itemStatusBar13Widths);
    itemBoxSizer2->Add(itemStatusBar13, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

////@end Queries_PANEL content construction
}


/*!
 * Should we show tooltips?
 */

bool Queries_PANEL::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap Queries_PANEL::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin Queries_PANEL bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end Queries_PANEL bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon Queries_PANEL::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin Queries_PANEL icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end Queries_PANEL icon retrieval
}
