/////////////////////////////////////////////////////////////////////////////
// Name:        zoomtocoordinate.cpp
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Mon 22 Oct 11:30:06 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 22 Oct 11:30:06 2007

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "zoomtocoordinate.h"

////@begin XPM images
////@end XPM images


/*!
 * Zoomtocoordinate type definition
 */

IMPLEMENT_DYNAMIC_CLASS( Zoomtocoordinate, wxDialog )


/*!
 * Zoomtocoordinate event table definition
 */

BEGIN_EVENT_TABLE( Zoomtocoordinate, wxDialog )

////@begin Zoomtocoordinate event table entries
////@end Zoomtocoordinate event table entries

END_EVENT_TABLE()


/*!
 * Zoomtocoordinate constructors
 */

Zoomtocoordinate::Zoomtocoordinate()
{
    Init();
}

Zoomtocoordinate::Zoomtocoordinate( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}


/*!
 * Zoomtocoordinate creator
 */

bool Zoomtocoordinate::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin Zoomtocoordinate creation
    SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end Zoomtocoordinate creation
    return true;
}


/*!
 * Zoomtocoordinate destructor
 */

Zoomtocoordinate::~Zoomtocoordinate()
{
////@begin Zoomtocoordinate destruction
////@end Zoomtocoordinate destruction
}


/*!
 * Member initialisation
 */

void Zoomtocoordinate::Init()
{
////@begin Zoomtocoordinate member initialisation
////@end Zoomtocoordinate member initialisation
}


/*!
 * Control creation for Zoomtocoordinate
 */

void Zoomtocoordinate::CreateControls()
{    
////@begin Zoomtocoordinate content construction
    // Generated by DialogBlocks, Mon 22 Oct 11:37:15 2007 (Personal Edition)

    Zoomtocoordinate* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    wxStaticBox* itemStaticBoxSizer3Static = new wxStaticBox(itemDialog1, wxID_ANY, _("Coordinates"));
    wxStaticBoxSizer* itemStaticBoxSizer3 = new wxStaticBoxSizer(itemStaticBoxSizer3Static, wxVERTICAL);
    itemBoxSizer2->Add(itemStaticBoxSizer3, 0, wxGROW|wxALL, 5);

    wxFlexGridSizer* itemFlexGridSizer4 = new wxFlexGridSizer(2, 2, 0, 0);
    itemFlexGridSizer4->AddGrowableCol(1);
    itemStaticBoxSizer3->Add(itemFlexGridSizer4, 0, wxGROW|wxALL, 5);

    wxStaticText* itemStaticText5 = new wxStaticText( itemDialog1, wxID_STATIC, _("X :"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer4->Add(itemStaticText5, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxTextCtrl* itemTextCtrl6 = new wxTextCtrl( itemDialog1, ID_TEXTCTRL22, _T(""), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer4->Add(itemTextCtrl6, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText7 = new wxStaticText( itemDialog1, wxID_STATIC, _("Y :"), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer4->Add(itemStaticText7, 0, wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxTextCtrl* itemTextCtrl8 = new wxTextCtrl( itemDialog1, ID_TEXTCTRL23, _T(""), wxDefaultPosition, wxDefaultSize, 0 );
    itemFlexGridSizer4->Add(itemTextCtrl8, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticBox* itemStaticBoxSizer9Static = new wxStaticBox(itemDialog1, wxID_ANY, _("Scale"));
    wxStaticBoxSizer* itemStaticBoxSizer9 = new wxStaticBoxSizer(itemStaticBoxSizer9Static, wxVERTICAL);
    itemBoxSizer2->Add(itemStaticBoxSizer9, 1, wxGROW|wxALL, 5);

    wxArrayString itemListBox10Strings;
    wxListBox* itemListBox10 = new wxListBox( itemDialog1, ID_LISTBOX7, wxDefaultPosition, wxDefaultSize, itemListBox10Strings, wxLB_SINGLE );
    itemStaticBoxSizer9->Add(itemListBox10, 1, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer11 = new wxBoxSizer(wxHORIZONTAL);
    itemStaticBoxSizer9->Add(itemBoxSizer11, 0, wxGROW|wxALL, 5);

    wxStaticText* itemStaticText12 = new wxStaticText( itemDialog1, wxID_STATIC, _("Other scale :  1:"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer11->Add(itemStaticText12, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxTextCtrl* itemTextCtrl13 = new wxTextCtrl( itemDialog1, ID_TEXTCTRL24, _T(""), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer11->Add(itemTextCtrl13, 1, wxALIGN_CENTER_VERTICAL|wxRIGHT|wxTOP|wxBOTTOM, 5);

    wxBoxSizer* itemBoxSizer14 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer14, 0, wxALIGN_RIGHT|wxALL, 5);

    wxButton* itemButton15 = new wxButton( itemDialog1, wxID_CANCEL, _("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer14->Add(itemButton15, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton16 = new wxButton( itemDialog1, ID_BUTTON3, _("&Zoom"), wxDefaultPosition, wxDefaultSize, 0 );
    itemButton16->SetDefault();
    itemBoxSizer14->Add(itemButton16, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

////@end Zoomtocoordinate content construction
}


/*!
 * Should we show tooltips?
 */

bool Zoomtocoordinate::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap Zoomtocoordinate::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin Zoomtocoordinate bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end Zoomtocoordinate bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon Zoomtocoordinate::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin Zoomtocoordinate icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end Zoomtocoordinate icon retrieval
}
