/////////////////////////////////////////////////////////////////////////////
// Name:        addfield.cpp
// Purpose:
// Author:      Lucien Schreiber
// Modified by:
// Created:     Mon 20 Aug 15:04:17 2007
// RCS-ID:
// Copyright:   (c) CREALP 2007
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 20 Aug 15:04:17 2007

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "addfield.h"

////@begin XPM images
////@end XPM images

/*!
 * ProjectDefFieldDlg type definition
 */

IMPLEMENT_DYNAMIC_CLASS(ProjectDefFieldDlg, wxDialog)

/*!
 * ProjectDefFieldDlg event table definition
 */

BEGIN_EVENT_TABLE(ProjectDefFieldDlg, wxDialog)

////@begin ProjectDefFieldDlg event table entries
////@end ProjectDefFieldDlg event table entries

END_EVENT_TABLE()

/*!
 * ProjectDefFieldDlg constructors
 */

ProjectDefFieldDlg::ProjectDefFieldDlg() {
  Init();
}

ProjectDefFieldDlg::ProjectDefFieldDlg(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos,
                                       const wxSize& size, long style) {
  Init();
  Create(parent, id, caption, pos, size, style);
}

/*!
 * wxDialog creator
 */

bool ProjectDefFieldDlg::Create(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos,
                                const wxSize& size, long style) {
  ////@begin ProjectDefFieldDlg creation
  SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
  wxDialog::Create(parent, id, caption, pos, size, style);

  CreateControls();
  if (GetSizer()) {
    GetSizer()->SetSizeHints(this);
  }
  Centre();
  ////@end ProjectDefFieldDlg creation
  return true;
}

/*!
 * ProjectDefFieldDlg destructor
 */

ProjectDefFieldDlg::~ProjectDefFieldDlg() {
  ////@begin ProjectDefFieldDlg destruction
  ////@end ProjectDefFieldDlg destruction
}

/*!
 * Member initialisation
 */

void ProjectDefFieldDlg::Init() {
  ////@begin ProjectDefFieldDlg member initialisation
  m_DlgAFD_Field_Def = NULL;
  m_DlgAFD_Field_Type = NULL;
  m_DlgAFD_Field_Precision = NULL;
  m_DlgAFD_Field_Scale = NULL;
  m_DlgAFD_Result = NULL;
  m_DlgAFD_Field_Orientation = NULL;
  m_DlgAFD_Constrain_Values = NULL;
  m_DlgAFD_Constrain_Panel = NULL;
  m_DlgAFD_Coded_Val_List = NULL;
  ////@end ProjectDefFieldDlg member initialisation
}

/*!
 * Control creation for wxDialog
 */

void ProjectDefFieldDlg::CreateControls() {
  ////@begin ProjectDefFieldDlg content construction
  // Generated by DialogBlocks, Tue 8 Apr 18:43:32 2008 (Personal Edition)

  ProjectDefFieldDlg* itemDialog1 = this;

  wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
  itemDialog1->SetSizer(itemBoxSizer2);

  wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxHORIZONTAL);
  itemBoxSizer2->Add(itemBoxSizer3, 0, wxGROW | wxALL, 5);

  wxStaticText* itemStaticText4 =
      new wxStaticText(itemDialog1, wxID_STATIC, _("Field name :"), wxDefaultPosition, wxDefaultSize, 0);
  itemBoxSizer3->Add(itemStaticText4, 0, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  m_DlgAFD_Field_Def = new wxTextCtrl(itemDialog1, ID_DLGAFD_FIELD_DEF, _T(""), wxDefaultPosition, wxSize(200, -1), 0);
  itemBoxSizer3->Add(m_DlgAFD_Field_Def, 1, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxStaticBox* itemStaticBoxSizer6Static = new wxStaticBox(itemDialog1, wxID_ANY, _("Field properties"));
  wxStaticBoxSizer* itemStaticBoxSizer6 = new wxStaticBoxSizer(itemStaticBoxSizer6Static, wxVERTICAL);
  itemBoxSizer2->Add(itemStaticBoxSizer6, 0, wxGROW | wxALL, 5);

  wxFlexGridSizer* itemFlexGridSizer7 = new wxFlexGridSizer(4, 2, 0, 0);
  itemFlexGridSizer7->AddGrowableCol(1);
  itemStaticBoxSizer6->Add(itemFlexGridSizer7, 0, wxGROW, 5);

  wxStaticText* itemStaticText8 =
      new wxStaticText(itemDialog1, wxID_STATIC, _("Data Type :"), wxDefaultPosition, wxDefaultSize, 0);
  itemFlexGridSizer7->Add(itemStaticText8, 0, wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxArrayString m_DlgAFD_Field_TypeStrings;
  m_DlgAFD_Field_TypeStrings.Add(_("Integer"));
  m_DlgAFD_Field_TypeStrings.Add(_("Float"));
  m_DlgAFD_Field_TypeStrings.Add(_("Text"));
  m_DlgAFD_Field_TypeStrings.Add(_("Date"));
  m_DlgAFD_Field_Type =
      new wxChoice(itemDialog1, ID_DLGAFD_DATA_TYPE, wxDefaultPosition, wxDefaultSize, m_DlgAFD_Field_TypeStrings, 0);
  m_DlgAFD_Field_Type->SetStringSelection(_("Text"));
  itemFlexGridSizer7->Add(m_DlgAFD_Field_Type, 0, wxGROW | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxStaticText* itemStaticText10 =
      new wxStaticText(itemDialog1, wxID_STATIC, _("Field precision :"), wxDefaultPosition, wxDefaultSize, 0);
  itemFlexGridSizer7->Add(itemStaticText10, 0, wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  m_DlgAFD_Field_Precision = new wxSpinCtrl(itemDialog1, ID_DLGAFD_FIELD_PRECISION, _T("0"), wxDefaultPosition,
                                            wxDefaultSize, wxSP_ARROW_KEYS, 0, 100, 0);
  itemFlexGridSizer7->Add(m_DlgAFD_Field_Precision, 0, wxGROW | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxStaticText* itemStaticText12 =
      new wxStaticText(itemDialog1, wxID_STATIC, _("Field scale :"), wxDefaultPosition, wxDefaultSize, 0);
  itemFlexGridSizer7->Add(itemStaticText12, 0, wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  m_DlgAFD_Field_Scale = new wxSpinCtrl(itemDialog1, ID_DLGAFD_FIELD_SCALE, _T("0"), wxDefaultPosition, wxDefaultSize,
                                        wxSP_ARROW_KEYS, 0, 100, 0);
  itemFlexGridSizer7->Add(m_DlgAFD_Field_Scale, 0, wxGROW | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxStaticText* itemStaticText14 =
      new wxStaticText(itemDialog1, wxID_STATIC, _("Result sample :"), wxDefaultPosition, wxDefaultSize, 0);
  itemFlexGridSizer7->Add(itemStaticText14, 0, wxALIGN_LEFT | wxALIGN_TOP | wxALL, 5);

  m_DlgAFD_Result =
      new wxTextCtrl(itemDialog1, ID_DLGAFD_RESULT, _T(""), wxDefaultPosition, wxDefaultSize, wxTE_CENTRE);
  itemFlexGridSizer7->Add(m_DlgAFD_Result, 0, wxGROW | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  m_DlgAFD_Field_Orientation = new wxCheckBox(itemDialog1, ID_DLGAFD_ORIENTATION_FIELD, _("Orientation field"),
                                              wxDefaultPosition, wxDefaultSize, 0);
  m_DlgAFD_Field_Orientation->SetValue(false);
  itemFlexGridSizer7->Add(m_DlgAFD_Field_Orientation, 0, wxGROW | wxALIGN_CENTER_VERTICAL | wxLEFT | wxRIGHT | wxTOP,
                          5);

  m_DlgAFD_Constrain_Values = new wxCheckBox(itemDialog1, ID_DLGAFD_CONSTRAIN_VALUES, _("Constrain allowed values"),
                                             wxDefaultPosition, wxDefaultSize, 0);
  m_DlgAFD_Constrain_Values->SetValue(false);
  itemBoxSizer2->Add(m_DlgAFD_Constrain_Values, 0, wxGROW | wxALL, 5);

  m_DlgAFD_Constrain_Panel =
      new wxPanel(itemDialog1, ID_DLGAFD_CONSTRAIN_PANL, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
  itemBoxSizer2->Add(m_DlgAFD_Constrain_Panel, 0, wxALIGN_CENTER_HORIZONTAL, 5);

  wxStaticBox* itemStaticBoxSizer19Static = new wxStaticBox(m_DlgAFD_Constrain_Panel, wxID_ANY, _("Allowed values"));
  wxStaticBoxSizer* itemStaticBoxSizer19 = new wxStaticBoxSizer(itemStaticBoxSizer19Static, wxVERTICAL);
  m_DlgAFD_Constrain_Panel->SetSizer(itemStaticBoxSizer19);

  m_DlgAFD_Coded_Val_List = new ProjectDefFieldList(m_DlgAFD_Constrain_Panel, ID_DLGAFD_CODED_VAL_LIST,
                                                    wxDefaultPosition, wxSize(100, 200), wxLC_REPORT);
  itemStaticBoxSizer19->Add(m_DlgAFD_Coded_Val_List, 1, wxGROW | wxLEFT | wxRIGHT, 5);

  wxBoxSizer* itemBoxSizer21 = new wxBoxSizer(wxHORIZONTAL);
  itemStaticBoxSizer19->Add(itemBoxSizer21, 0, wxGROW | wxALL, 5);

  wxFlatButton* itemFlatButton22 =
      new wxFlatButton(m_DlgAFD_Constrain_Panel, ID_DLGAFD_VAL_ADD, _("+"), wxDefaultPosition, wxSize(40, -1), 0);
  itemFlatButton22->SetValue(false);
  itemBoxSizer21->Add(itemFlatButton22, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT | wxTOP | wxBOTTOM, 5);

  wxFlatButton* itemFlatButton23 =
      new wxFlatButton(m_DlgAFD_Constrain_Panel, ID_DLGAFD_VAL_REMOVE, _("-"), wxDefaultPosition, wxSize(40, -1), 0);
  itemFlatButton23->SetValue(false);
  itemBoxSizer21->Add(itemFlatButton23, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT | wxTOP | wxBOTTOM, 5);

  wxFlatButton* itemFlatButton24 = new wxFlatButton(m_DlgAFD_Constrain_Panel, ID_DLGAFD_VAL_IMPORT, _("Import..."),
                                                    wxDefaultPosition, wxDefaultSize, 0);
  itemFlatButton24->SetValue(false);
  itemBoxSizer21->Add(itemFlatButton24, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT | wxTOP | wxBOTTOM, 5);

  wxFlatButton* itemFlatButton25 = new wxFlatButton(m_DlgAFD_Constrain_Panel, ID_DLGAFD_VAL_EXPORT, _("Export..."),
                                                    wxDefaultPosition, wxDefaultSize, 0);
  itemFlatButton25->SetValue(false);
  itemBoxSizer21->Add(itemFlatButton25, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT | wxTOP | wxBOTTOM, 5);

  wxStdDialogButtonSizer* itemStdDialogButtonSizer26 = new wxStdDialogButtonSizer;

  itemBoxSizer2->Add(itemStdDialogButtonSizer26, 0, wxALIGN_RIGHT | wxALL, 5);
  wxButton* itemButton27 = new wxButton(itemDialog1, wxID_CANCEL, _("&Cancel"), wxDefaultPosition, wxDefaultSize, 0);
  itemStdDialogButtonSizer26->AddButton(itemButton27);

  wxButton* itemButton28 = new wxButton(itemDialog1, wxID_OK, _("&OK"), wxDefaultPosition, wxDefaultSize, 0);
  itemStdDialogButtonSizer26->AddButton(itemButton28);

  itemStdDialogButtonSizer26->Realize();

  ////@end ProjectDefFieldDlg content construction
}

/*!
 * Should we show tooltips?
 */

bool ProjectDefFieldDlg::ShowToolTips() {
  return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap ProjectDefFieldDlg::GetBitmapResource(const wxString& name) {
  // Bitmap retrieval
  ////@begin ProjectDefFieldDlg bitmap retrieval
  wxUnusedVar(name);
  return wxNullBitmap;
  ////@end ProjectDefFieldDlg bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon ProjectDefFieldDlg::GetIconResource(const wxString& name) {
  // Icon retrieval
  ////@begin ProjectDefFieldDlg icon retrieval
  wxUnusedVar(name);
  return wxNullIcon;
  ////@end ProjectDefFieldDlg icon retrieval
}
