/////////////////////////////////////////////////////////////////////////////
// Name:        adjustshortcuts.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Fri 28 Sep 12:54:12 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Fri 28 Sep 12:54:12 2007

#ifndef _ADJUSTSHORTCUTS_H_
#define _ADJUSTSHORTCUTS_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/notebook.h"
#include "wx/tglbtn.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ADJUSTSHORTCUTS 10186
#define ID_NOTEBOOK8 10187
#define ID_PANEL20 10188
#define ID_LISTBOX4 10189
#define ID_TOGGLEBUTTON23 10242
#define ID_TOGGLEBUTTON24 10192
#define ID_PANEL21 10190
#define ID_LISTBOX 10000
#define ID_TOGGLEBUTTON 10002
#define ID_TOGGLEBUTTON1 10003
#define ID_PANEL22 10191
#define ID_LISTBOX1 10001
#define ID_TOGGLEBUTTON2 10004
#define ID_TOGGLEBUTTON3 10005
#define SYMBOL_ADJUSTSHORTCUTS_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_ADJUSTSHORTCUTS_TITLE _("Shortcuts")
#define SYMBOL_ADJUSTSHORTCUTS_IDNAME ID_ADJUSTSHORTCUTS
#define SYMBOL_ADJUSTSHORTCUTS_SIZE wxSize(400, 300)
#define SYMBOL_ADJUSTSHORTCUTS_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * Adjustshortcuts class declaration
 */

class Adjustshortcuts: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( Adjustshortcuts )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    Adjustshortcuts();
    Adjustshortcuts( wxWindow* parent, wxWindowID id = SYMBOL_ADJUSTSHORTCUTS_IDNAME, const wxString& caption = SYMBOL_ADJUSTSHORTCUTS_TITLE, const wxPoint& pos = SYMBOL_ADJUSTSHORTCUTS_POSITION, const wxSize& size = SYMBOL_ADJUSTSHORTCUTS_SIZE, long style = SYMBOL_ADJUSTSHORTCUTS_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ADJUSTSHORTCUTS_IDNAME, const wxString& caption = SYMBOL_ADJUSTSHORTCUTS_TITLE, const wxPoint& pos = SYMBOL_ADJUSTSHORTCUTS_POSITION, const wxSize& size = SYMBOL_ADJUSTSHORTCUTS_SIZE, long style = SYMBOL_ADJUSTSHORTCUTS_STYLE );

    /// Destructor
    ~Adjustshortcuts();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin Adjustshortcuts event handler declarations

////@end Adjustshortcuts event handler declarations

////@begin Adjustshortcuts member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end Adjustshortcuts member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin Adjustshortcuts member variables
////@end Adjustshortcuts member variables
};

#endif
    // _ADJUSTSHORTCUTS_H_
