/////////////////////////////////////////////////////////////////////////////
// Name:        complexattribution.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Tue 28 Aug 17:19:19 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Tue 28 Aug 17:19:19 2007

#ifndef _COMPLEXATTRIBUTION_H_
#define _COMPLEXATTRIBUTION_H_

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_COMPLEXATTRIBUTION 10143
#define ID_LISTBOX3 10144
#define ID_BUTTON21 10146
#define SYMBOL_COMPLEXATTRIBUTION_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_COMPLEXATTRIBUTION_TITLE _("Object attributes")
#define SYMBOL_COMPLEXATTRIBUTION_IDNAME ID_COMPLEXATTRIBUTION
#define SYMBOL_COMPLEXATTRIBUTION_SIZE wxSize(400, 300)
#define SYMBOL_COMPLEXATTRIBUTION_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * Complexattribution class declaration
 */

class Complexattribution: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( Complexattribution )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    Complexattribution();
    Complexattribution( wxWindow* parent, wxWindowID id = SYMBOL_COMPLEXATTRIBUTION_IDNAME, const wxString& caption = SYMBOL_COMPLEXATTRIBUTION_TITLE, const wxPoint& pos = SYMBOL_COMPLEXATTRIBUTION_POSITION, const wxSize& size = SYMBOL_COMPLEXATTRIBUTION_SIZE, long style = SYMBOL_COMPLEXATTRIBUTION_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_COMPLEXATTRIBUTION_IDNAME, const wxString& caption = SYMBOL_COMPLEXATTRIBUTION_TITLE, const wxPoint& pos = SYMBOL_COMPLEXATTRIBUTION_POSITION, const wxSize& size = SYMBOL_COMPLEXATTRIBUTION_SIZE, long style = SYMBOL_COMPLEXATTRIBUTION_STYLE );

    /// Destructor
    ~Complexattribution();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin Complexattribution event handler declarations

////@end Complexattribution event handler declarations

////@begin Complexattribution member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end Complexattribution member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin Complexattribution member variables
////@end Complexattribution member variables
};

#endif
    // _COMPLEXATTRIBUTION_H_
