/////////////////////////////////////////////////////////////////////////////
// Name:        dlg_attribution.h
// Purpose:
// Author:      Lucien Schreiber
// Modified by:
// Created:     Mon  6 Aug 15:19:35 2007
// RCS-ID:
// Copyright:   (c) CREALP 2007
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 6 Aug 15:19:35 2007

#ifndef _DLG_ATTRIBUTION_H_
#define _DLG_ATTRIBUTION_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/listctrl.h"
#include "wx/notebook.h"
#include "wx/statline.h"
#include "wx/tglbtn.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxNotebook;
class ListParam;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DLG_ATTRIBUTION 10025
#define ID_DLGPEO_NOTEBOOK 10026
#define ID_DLGPEO_PANEL_LINE 10027
#define ID_DLGPEO_LISTLINE 10264
#define ID_DLGPEO_LYR_NAME_LINE 10234
#define ID_DLGPEO_LINE_FRQ 10235
#define ID_DLGPEO_PANEL_POINT 10028
#define ID_DLGPEO_LISTPOINT 10000
#define ID_DLGPEO_LYR_NAME_POINT 10234
#define ID_DLGPEO_PANEL_POLY 10029
#define ID_DLGPEO_LISTPOLY 10000
#define ID_DLGPEO_LYR_NAME_POLY 10234
#define ID_TOGGLEBUTTON8 10031
#define ID_TOGGLEBUTTON9 10032
#define ID_TOGGLEBUTTON10 10232
#define ID_TOGGLEBUTTON11 10233
#define SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_STYLE \
  wxCAPTION | wxRESIZE_BORDER | wxSYSTEM_MENU | wxCLOSE_BOX | wxMAXIMIZE_BOX
#define SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_TITLE _("Objects definition")
#define SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_IDNAME ID_DLG_ATTRIBUTION
#define SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_SIZE wxDefaultSize
#define SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * ProjectEditObjectDefinitionDLG class declaration
 */

class ProjectEditObjectDefinitionDLG : public wxDialog {
  DECLARE_DYNAMIC_CLASS(ProjectEditObjectDefinitionDLG)
  DECLARE_EVENT_TABLE()

 public:
  /// Constructors
  ProjectEditObjectDefinitionDLG();
  ProjectEditObjectDefinitionDLG(wxWindow* parent, wxWindowID id = SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_IDNAME,
                                 const wxString& caption = SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_TITLE,
                                 const wxPoint& pos = SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_POSITION,
                                 const wxSize& size = SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_SIZE,
                                 long style = SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_STYLE);

  /// Creation
  bool Create(wxWindow* parent, wxWindowID id = SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_IDNAME,
              const wxString& caption = SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_TITLE,
              const wxPoint& pos = SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_POSITION,
              const wxSize& size = SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_SIZE,
              long style = SYMBOL_PROJECTEDITOBJECTDEFINITIONDLG_STYLE);

  /// Destructor
  ~ProjectEditObjectDefinitionDLG();

  /// Initialises member variables
  void Init();

  /// Creates the controls and sizers
  void CreateControls();

  ////@begin ProjectEditObjectDefinitionDLG event handler declarations

  ////@end ProjectEditObjectDefinitionDLG event handler declarations

  ////@begin ProjectEditObjectDefinitionDLG member function declarations

  /// Retrieves bitmap resources
  wxBitmap GetBitmapResource(const wxString& name);

  /// Retrieves icon resources
  wxIcon GetIconResource(const wxString& name);
  ////@end ProjectEditObjectDefinitionDLG member function declarations

  /// Should we show tooltips?
  static bool ShowToolTips();

  ////@begin ProjectEditObjectDefinitionDLG member variables
  wxNotebook* m_DLGPEO_Notebook;
  wxPanel* m_DLGPEO_Panel_Line;
  ListParam* m_DLGPEO_List_Line;
  wxChoice* m_DLGPEO_Choice_Lyr_Line_Name;
  wxCheckBox* m_DLGPEO_Choice_Lyr_Line_Freq;
  wxPanel* m_DLGPEO_Panel_Point;
  ListParam* m_DLGPEO_List_Line;
  wxChoice* m_DLGPEO_Choice_Lyr_Point_Name;
  wxPanel* m_DLGPEO_Panel_Poly;
  ListParam* m_DLGPEO_List_Line;
  wxChoice* m_DLGPEO_Choice_Lyr_Poly_Name;
  ////@end ProjectEditObjectDefinitionDLG member variables
};

#endif
// _DLG_ATTRIBUTION_H_
