/////////////////////////////////////////////////////////////////////////////
// Name:        importlog.cpp
// Purpose:
// Author:      Lucien Schreiber
// Modified by:
// Created:     Thu 30 Aug 14:52:41 2007
// RCS-ID:
// Copyright:   (c) CREALP 2007
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Thu 30 Aug 14:52:41 2007

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "importlog.h"

////@begin XPM images
////@end XPM images

/*!
 * ImportLog type definition
 */

IMPLEMENT_DYNAMIC_CLASS(ImportLog, wxDialog)

/*!
 * ImportLog event table definition
 */

BEGIN_EVENT_TABLE(ImportLog, wxDialog)

////@begin ImportLog event table entries
////@end ImportLog event table entries

END_EVENT_TABLE()

/*!
 * ImportLog constructors
 */

ImportLog::ImportLog() {
  Init();
}

ImportLog::ImportLog(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size,
                     long style) {
  Init();
  Create(parent, id, caption, pos, size, style);
}

/*!
 * ImportLog creator
 */

bool ImportLog::Create(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size,
                       long style) {
  ////@begin ImportLog creation
  SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
  wxDialog::Create(parent, id, caption, pos, size, style);

  CreateControls();
  if (GetSizer()) {
    GetSizer()->SetSizeHints(this);
  }
  Centre();
  ////@end ImportLog creation
  return true;
}

/*!
 * ImportLog destructor
 */

ImportLog::~ImportLog() {
  ////@begin ImportLog destruction
  ////@end ImportLog destruction
}

/*!
 * Member initialisation
 */

void ImportLog::Init() {
  ////@begin ImportLog member initialisation
  ////@end ImportLog member initialisation
}

/*!
 * Control creation for ImportLog
 */

void ImportLog::CreateControls() {
  ////@begin ImportLog content construction
  // Generated by DialogBlocks, Mon 3 Dec 14:55:48 2007 (Personal Edition)

  ImportLog* itemDialog1 = this;

  wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
  itemDialog1->SetSizer(itemBoxSizer2);

  wxStaticBox* itemStaticBoxSizer3Static = new wxStaticBox(itemDialog1, wxID_ANY, _("Program log"));
  wxStaticBoxSizer* itemStaticBoxSizer3 = new wxStaticBoxSizer(itemStaticBoxSizer3Static, wxVERTICAL);
  itemBoxSizer2->Add(itemStaticBoxSizer3, 1, wxGROW | wxALL, 5);

  wxTextCtrl* itemTextCtrl4 =
      new wxTextCtrl(itemDialog1, ID_DLGLOG_TXT, _T(""), wxDefaultPosition, wxSize(400, 200), wxTE_MULTILINE);
  itemStaticBoxSizer3->Add(itemTextCtrl4, 1, wxGROW | wxALL, 5);

  wxButton* itemButton5 = new wxButton(itemDialog1, wxID_CLOSE, _("&Close"), wxDefaultPosition, wxDefaultSize, 0);
  itemButton5->SetDefault();
  itemBoxSizer2->Add(itemButton5, 0, wxALIGN_RIGHT | wxALL, 5);

  ////@end ImportLog content construction
}

/*!
 * Should we show tooltips?
 */

bool ImportLog::ShowToolTips() {
  return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap ImportLog::GetBitmapResource(const wxString& name) {
  // Bitmap retrieval
  ////@begin ImportLog bitmap retrieval
  wxUnusedVar(name);
  return wxNullBitmap;
  ////@end ImportLog bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon ImportLog::GetIconResource(const wxString& name) {
  // Icon retrieval
  ////@begin ImportLog icon retrieval
  wxUnusedVar(name);
  return wxNullIcon;
  ////@end ImportLog icon retrieval
}
