/////////////////////////////////////////////////////////////////////////////
// Name:        importdata.h
// Purpose:
// Author:      Lucien Schreiber
// Modified by:
// Created:     Fri 24 Aug 14:50:18 2007
// RCS-ID:
// Copyright:   (c) CREALP 2007
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Fri 24 Aug 14:50:18 2007

#ifndef _IMPORTDATA_H_
#define _IMPORTDATA_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/notebook.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_IMPORTDATA 10102
#define ID_NOTEBOOK6 10103
#define ID_PANEL14 10104
#define ID_TEXTCTRL 10000
#define ID_BUTTON 10001
#define ID_CHECKBOX3 10105
#define ID_LISTBOX1 10106
#define ID_CHOICE18 10238
#define ID_PANEL15 10107
#define ID_TEXTCTRL11 10108
#define ID_BUTTON18 10109
#define SYMBOL_IMPORTDATA_STYLE wxCAPTION | wxRESIZE_BORDER | wxSYSTEM_MENU | wxCLOSE_BOX
#define SYMBOL_IMPORTDATA_TITLE _("Import data")
#define SYMBOL_IMPORTDATA_IDNAME ID_IMPORTDATA
#define SYMBOL_IMPORTDATA_SIZE wxSize(400, 300)
#define SYMBOL_IMPORTDATA_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Importdata class declaration
 */

class Importdata : public wxDialog {
  DECLARE_DYNAMIC_CLASS(Importdata)
  DECLARE_EVENT_TABLE()

 public:
  /// Constructors
  Importdata();
  Importdata(wxWindow* parent, wxWindowID id = SYMBOL_IMPORTDATA_IDNAME,
             const wxString& caption = SYMBOL_IMPORTDATA_TITLE, const wxPoint& pos = SYMBOL_IMPORTDATA_POSITION,
             const wxSize& size = SYMBOL_IMPORTDATA_SIZE, long style = SYMBOL_IMPORTDATA_STYLE);

  /// Creation
  bool Create(wxWindow* parent, wxWindowID id = SYMBOL_IMPORTDATA_IDNAME,
              const wxString& caption = SYMBOL_IMPORTDATA_TITLE, const wxPoint& pos = SYMBOL_IMPORTDATA_POSITION,
              const wxSize& size = SYMBOL_IMPORTDATA_SIZE, long style = SYMBOL_IMPORTDATA_STYLE);

  /// Destructor
  ~Importdata();

  /// Initialises member variables
  void Init();

  /// Creates the controls and sizers
  void CreateControls();

  ////@begin Importdata event handler declarations

  ////@end Importdata event handler declarations

  ////@begin Importdata member function declarations

  /// Retrieves bitmap resources
  wxBitmap GetBitmapResource(const wxString& name);

  /// Retrieves icon resources
  wxIcon GetIconResource(const wxString& name);
  ////@end Importdata member function declarations

  /// Should we show tooltips?
  static bool ShowToolTips();

  ////@begin Importdata member variables
  ////@end Importdata member variables
};

#endif
// _IMPORTDATA_H_
