/////////////////////////////////////////////////////////////////////////////
// Name:        informations.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Mon 27 Aug 14:56:56 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 27 Aug 14:56:56 2007

#ifndef _INFORMATIONS_H_
#define _INFORMATIONS_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/statline.h"
#include "wx/statusbr.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_INFORMATIONS 10128
#define ID_CHOICE9 10129
#define ID_STATICLINE 10130
#define ID_STATUSBAR 10000
#define SYMBOL_INFORMATIONS_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_INFORMATIONS_TITLE _("Informations")
#define SYMBOL_INFORMATIONS_IDNAME ID_INFORMATIONS
#define SYMBOL_INFORMATIONS_SIZE wxSize(400, 300)
#define SYMBOL_INFORMATIONS_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * Informations class declaration
 */

class Informations: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( Informations )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    Informations();
    Informations( wxWindow* parent, wxWindowID id = SYMBOL_INFORMATIONS_IDNAME, const wxString& caption = SYMBOL_INFORMATIONS_TITLE, const wxPoint& pos = SYMBOL_INFORMATIONS_POSITION, const wxSize& size = SYMBOL_INFORMATIONS_SIZE, long style = SYMBOL_INFORMATIONS_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_INFORMATIONS_IDNAME, const wxString& caption = SYMBOL_INFORMATIONS_TITLE, const wxPoint& pos = SYMBOL_INFORMATIONS_POSITION, const wxSize& size = SYMBOL_INFORMATIONS_SIZE, long style = SYMBOL_INFORMATIONS_STYLE );

    /// Destructor
    ~Informations();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin Informations event handler declarations

////@end Informations event handler declarations

////@begin Informations member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end Informations member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin Informations member variables
////@end Informations member variables
};

#endif
    // _INFORMATIONS_H_
