/////////////////////////////////////////////////////////////////////////////
// Name:        main.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Tue 27 Nov 17:52:52 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Tue 27 Nov 17:52:52 2007

#ifndef _MAIN_H_
#define _MAIN_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/toolbar.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_MAIN 10024
#define ID_TOOLBAR1 10038
#define ID_TOOL1 10071
#define ID_TOOL2 10073
#define SYMBOL_MAIN_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_MAIN_TITLE _("main")
#define SYMBOL_MAIN_IDNAME ID_MAIN
#define SYMBOL_MAIN_SIZE wxSize(400, 300)
#define SYMBOL_MAIN_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * main class declaration
 */

class main: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( main )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    main();
    main( wxWindow* parent, wxWindowID id = SYMBOL_MAIN_IDNAME, const wxString& caption = SYMBOL_MAIN_TITLE, const wxPoint& pos = SYMBOL_MAIN_POSITION, const wxSize& size = SYMBOL_MAIN_SIZE, long style = SYMBOL_MAIN_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_MAIN_IDNAME, const wxString& caption = SYMBOL_MAIN_TITLE, const wxPoint& pos = SYMBOL_MAIN_POSITION, const wxSize& size = SYMBOL_MAIN_SIZE, long style = SYMBOL_MAIN_STYLE );

    /// Destructor
    ~main();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin main event handler declarations

////@end main event handler declarations

////@begin main member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end main member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin main member variables
////@end main member variables
};

#endif
    // _MAIN_H_
