/////////////////////////////////////////////////////////////////////////////
// Name:        mergelines.h
// Purpose:
// Author:      Lucien Schreiber
// Modified by:
// Created:     Thu 18 Oct 11:58:40 2007
// RCS-ID:
// Copyright:   (c) CREALP 2007
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Thu 18 Oct 11:58:40 2007

#ifndef _MERGELINES_H_
#define _MERGELINES_H_

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_MERGELINES 10121
#define ID_LISTBOX6 10226
#define SYMBOL_MERGELINES_STYLE wxCAPTION | wxRESIZE_BORDER | wxSYSTEM_MENU | wxCLOSE_BOX
#define SYMBOL_MERGELINES_TITLE _("Merge lines")
#define SYMBOL_MERGELINES_IDNAME ID_MERGELINES
#define SYMBOL_MERGELINES_SIZE wxSize(400, 300)
#define SYMBOL_MERGELINES_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Mergelines class declaration
 */

class Mergelines : public wxDialog {
  DECLARE_DYNAMIC_CLASS(Mergelines)
  DECLARE_EVENT_TABLE()

 public:
  /// Constructors
  Mergelines();
  Mergelines(wxWindow* parent, wxWindowID id = SYMBOL_MERGELINES_IDNAME,
             const wxString& caption = SYMBOL_MERGELINES_TITLE, const wxPoint& pos = SYMBOL_MERGELINES_POSITION,
             const wxSize& size = SYMBOL_MERGELINES_SIZE, long style = SYMBOL_MERGELINES_STYLE);

  /// Creation
  bool Create(wxWindow* parent, wxWindowID id = SYMBOL_MERGELINES_IDNAME,
              const wxString& caption = SYMBOL_MERGELINES_TITLE, const wxPoint& pos = SYMBOL_MERGELINES_POSITION,
              const wxSize& size = SYMBOL_MERGELINES_SIZE, long style = SYMBOL_MERGELINES_STYLE);

  /// Destructor
  ~Mergelines();

  /// Initialises member variables
  void Init();

  /// Creates the controls and sizers
  void CreateControls();

  ////@begin Mergelines event handler declarations

  ////@end Mergelines event handler declarations

  ////@begin Mergelines member function declarations

  /// Retrieves bitmap resources
  wxBitmap GetBitmapResource(const wxString& name);

  /// Retrieves icon resources
  wxIcon GetIconResource(const wxString& name);
  ////@end Mergelines member function declarations

  /// Should we show tooltips?
  static bool ShowToolTips();

  ////@begin Mergelines member variables
  ////@end Mergelines member variables
};

#endif
// _MERGELINES_H_
