/////////////////////////////////////////////////////////////////////////////
// Name:        newprojectfromexisting.cpp
// Purpose:
// Author:      Lucien Schreiber
// Modified by:
// Created:     Wed 29 Aug 08:42:46 2007
// RCS-ID:
// Copyright:   (c) CREALP 2007
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Wed 29 Aug 08:42:46 2007

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "newprojectfromexisting.h"

////@begin XPM images
////@end XPM images

/*!
 * ProjectNewExistDLG type definition
 */

IMPLEMENT_DYNAMIC_CLASS(ProjectNewExistDLG, wxDialog)

/*!
 * ProjectNewExistDLG event table definition
 */

BEGIN_EVENT_TABLE(ProjectNewExistDLG, wxDialog)

////@begin ProjectNewExistDLG event table entries
////@end ProjectNewExistDLG event table entries

END_EVENT_TABLE()

/*!
 * ProjectNewExistDLG constructors
 */

ProjectNewExistDLG::ProjectNewExistDLG() {
  Init();
}

ProjectNewExistDLG::ProjectNewExistDLG(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos,
                                       const wxSize& size, long style) {
  Init();
  Create(parent, id, caption, pos, size, style);
}

/*!
 * Newprojectfromexisting creator
 */

bool ProjectNewExistDLG::Create(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos,
                                const wxSize& size, long style) {
  ////@begin ProjectNewExistDLG creation
  SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
  wxDialog::Create(parent, id, caption, pos, size, style);

  CreateControls();
  if (GetSizer()) {
    GetSizer()->SetSizeHints(this);
  }
  Centre();
  ////@end ProjectNewExistDLG creation
  return true;
}

/*!
 * ProjectNewExistDLG destructor
 */

ProjectNewExistDLG::~ProjectNewExistDLG() {
  ////@begin ProjectNewExistDLG destruction
  ////@end ProjectNewExistDLG destruction
}

/*!
 * Member initialisation
 */

void ProjectNewExistDLG::Init() {
  ////@begin ProjectNewExistDLG member initialisation
  m_DlgPNE_New_Prj_Path = nullptr;
  m_DlgPNE_New_Prj_Name = nullptr;
  m_DlgPNE_Old_Prj_Path = nullptr;
  m_DlgPNE_Options = nullptr;
  m_DlgPNE_Btn_OK = nullptr;
  ////@end ProjectNewExistDLG member initialisation
}

/*!
 * Control creation for Newprojectfromexisting
 */

void ProjectNewExistDLG::CreateControls() {
  ////@begin ProjectNewExistDLG content construction
  ProjectNewExistDLG* itemDialog1 = this;

  wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
  itemDialog1->SetSizer(itemBoxSizer2);

  wxStaticBox* itemStaticBoxSizer3Static = new wxStaticBox(itemDialog1, wxID_ANY, _("New project properties"));
  wxStaticBoxSizer* itemStaticBoxSizer3 = new wxStaticBoxSizer(itemStaticBoxSizer3Static, wxVERTICAL);
  itemBoxSizer2->Add(itemStaticBoxSizer3, 0, wxGROW | wxALL, 5);

  wxFlexGridSizer* itemFlexGridSizer4 = new wxFlexGridSizer(2, 3, 0, 0);
  itemFlexGridSizer4->AddGrowableCol(1);
  itemStaticBoxSizer3->Add(itemFlexGridSizer4, 0, wxGROW | wxALL, 0);

  wxStaticText* itemStaticText5 =
      new wxStaticText(itemDialog1, wxID_STATIC, _("New project path :"), wxDefaultPosition, wxDefaultSize, 0);
  itemFlexGridSizer4->Add(itemStaticText5, 0, wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  m_DlgPNE_New_Prj_Path = new wxTextCtrl(itemDialog1, ID_TEXTCTRL15, _T(""), wxDefaultPosition, wxDefaultSize, 0);
  itemFlexGridSizer4->Add(m_DlgPNE_New_Prj_Path, 0, wxGROW | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxButton* itemButton7 =
      new wxButton(itemDialog1, ID_DLGNPE_NEW_PRJ_PATH_BTN, _("..."), wxDefaultPosition, wxDefaultSize, 0);
  itemFlexGridSizer4->Add(itemButton7, 0, wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxStaticText* itemStaticText8 =
      new wxStaticText(itemDialog1, wxID_STATIC, _("New project name :"), wxDefaultPosition, wxDefaultSize, 0);
  itemFlexGridSizer4->Add(itemStaticText8, 0, wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  m_DlgPNE_New_Prj_Name = new wxTextCtrl(itemDialog1, ID_TEXTCTRL16, _T(""), wxDefaultPosition, wxDefaultSize, 0);
  itemFlexGridSizer4->Add(m_DlgPNE_New_Prj_Name, 0, wxGROW | wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxStaticLine* itemStaticLine10 =
      new wxStaticLine(itemDialog1, ID_STATICLINE1, wxDefaultPosition, wxDefaultSize, wxLI_HORIZONTAL);
  itemBoxSizer2->Add(itemStaticLine10, 0, wxGROW | wxALL, 5);

  wxStaticBox* itemStaticBoxSizer11Static = new wxStaticBox(itemDialog1, wxID_ANY, _("Existing project path"));
  wxStaticBoxSizer* itemStaticBoxSizer11 = new wxStaticBoxSizer(itemStaticBoxSizer11Static, wxVERTICAL);
  itemBoxSizer2->Add(itemStaticBoxSizer11, 0, wxGROW | wxALL, 5);

  wxBoxSizer* itemBoxSizer12 = new wxBoxSizer(wxHORIZONTAL);
  itemStaticBoxSizer11->Add(itemBoxSizer12, 0, wxGROW | wxALL, 0);

  wxStaticText* itemStaticText13 =
      new wxStaticText(itemDialog1, wxID_STATIC, _("Existing project path :"), wxDefaultPosition, wxDefaultSize, 0);
  itemBoxSizer12->Add(itemStaticText13, 0, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  m_DlgPNE_Old_Prj_Path = new wxTextCtrl(itemDialog1, ID_TEXTCTRL17, _T(""), wxDefaultPosition, wxDefaultSize, 0);
  itemBoxSizer12->Add(m_DlgPNE_Old_Prj_Path, 1, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxButton* itemButton15 =
      new wxButton(itemDialog1, ID_DLGNPE_OLD_PRJ_PATH_BTN, _("..."), wxDefaultPosition, wxDefaultSize, 0);
  itemBoxSizer12->Add(itemButton15, 0, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxArrayString m_DlgPNE_OptionsStrings;
  m_DlgPNE_OptionsStrings.Add(_("&Keep only project structure"));
  m_DlgPNE_OptionsStrings.Add(_("&Keep project structure and data"));
  m_DlgPNE_Options = new wxRadioBox(itemDialog1, ID_DLGNPE_RADIO_OPTIONS, _("New project options"), wxDefaultPosition,
                                    wxDefaultSize, m_DlgPNE_OptionsStrings, 1, wxRA_SPECIFY_COLS);
  m_DlgPNE_Options->SetSelection(0);
  itemBoxSizer2->Add(m_DlgPNE_Options, 1, wxGROW | wxALL, 5);

  wxStdDialogButtonSizer* itemStdDialogButtonSizer17 = new wxStdDialogButtonSizer;

  itemBoxSizer2->Add(itemStdDialogButtonSizer17, 0, wxALIGN_RIGHT | wxALL, 5);
  m_DlgPNE_Btn_OK = new wxButton(itemDialog1, wxID_OK, _("&Create new project"), wxDefaultPosition, wxDefaultSize, 0);
  itemStdDialogButtonSizer17->AddButton(m_DlgPNE_Btn_OK);

  wxButton* itemButton19 = new wxButton(itemDialog1, wxID_CANCEL, _("&Cancel"), wxDefaultPosition, wxDefaultSize, 0);
  itemStdDialogButtonSizer17->AddButton(itemButton19);

  itemStdDialogButtonSizer17->Realize();

  ////@end ProjectNewExistDLG content construction
}

/*!
 * Should we show tooltips?
 */

bool ProjectNewExistDLG::ShowToolTips() {
  return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap ProjectNewExistDLG::GetBitmapResource(const wxString& name) {
  // Bitmap retrieval
  ////@begin ProjectNewExistDLG bitmap retrieval
  wxUnusedVar(name);
  return wxNullBitmap;
  ////@end ProjectNewExistDLG bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon ProjectNewExistDLG::GetIconResource(const wxString& name) {
  // Icon retrieval
  ////@begin ProjectNewExistDLG icon retrieval
  wxUnusedVar(name);
  return wxNullIcon;
  ////@end ProjectNewExistDLG icon retrieval
}
