/////////////////////////////////////////////////////////////////////////////
// Name:        newprojectfromexistant.h
// Purpose:
// Author:      Lucien Schreiber
// Modified by:
// Created:     Wed 29 Aug 08:44:12 2007
// RCS-ID:
// Copyright:   (c) CREALP 2007
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Wed 29 Aug 08:44:12 2007

#ifndef _NEWPROJECTFROMEXISTANT_H_
#define _NEWPROJECTFROMEXISTANT_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/wizard.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_NEWPROJECTFROMEXISTANT 10149
#define SYMBOL_NEWPROJECTFROMEXISTANT_IDNAME ID_NEWPROJECTFROMEXISTANT
////@end control identifiers

/*!
 * Newprojectfromexistant class declaration
 */

class Newprojectfromexistant : public wxWizard {
  DECLARE_DYNAMIC_CLASS(Newprojectfromexistant)
  DECLARE_EVENT_TABLE()

 public:
  /// Constructors
  Newprojectfromexistant();
  Newprojectfromexistant(wxWindow* parent, wxWindowID id = SYMBOL_NEWPROJECTFROMEXISTANT_IDNAME,
                         const wxPoint& pos = wxDefaultPosition);

  /// Creation
  bool Create(wxWindow* parent, wxWindowID id = SYMBOL_NEWPROJECTFROMEXISTANT_IDNAME,
              const wxPoint& pos = wxDefaultPosition);

  /// Destructor
  ~Newprojectfromexistant();

  /// Initialises member variables
  void Init();

  /// Creates the controls and sizers
  void CreateControls();

  ////@begin Newprojectfromexistant event handler declarations

  ////@end Newprojectfromexistant event handler declarations

  ////@begin Newprojectfromexistant member function declarations

  /// Runs the wizard
  bool Run();

  /// Retrieves bitmap resources
  wxBitmap GetBitmapResource(const wxString& name);

  /// Retrieves icon resources
  wxIcon GetIconResource(const wxString& name);
  ////@end Newprojectfromexistant member function declarations

  /// Should we show tooltips?
  static bool ShowToolTips();

  ////@begin Newprojectfromexistant member variables
  ////@end Newprojectfromexistant member variables
};

#endif
// _NEWPROJECTFROMEXISTANT_H_
