/////////////////////////////////////////////////////////////////////////////
// Name:        newproject.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Mon  6 Aug 17:03:00 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 6 Aug 17:03:00 2007

#ifndef _NEWPROJECT_H_
#define _NEWPROJECT_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/listctrl.h"
#include "wx/tglbtn.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_WXDIALOG 10000
#define ID_TEXTCTRL1 10001
#define ID_BUTTON1 10002
#define ID_TEXTCTRL2 10003
#define ID_CHOICE10 10156
#define ID_CHOICE8 10119
#define ID_LISTCTRL1 10004
#define ID_TOGGLEBUTTON5 10219
#define ID_TOGGLEBUTTON6 10220
#define SYMBOL_WXDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_WXDIALOG_TITLE _("Project Definition")
#define SYMBOL_WXDIALOG_IDNAME ID_WXDIALOG
#define SYMBOL_WXDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_WXDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * wxDialog class declaration
 */

class wxDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( wxDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxDialog();
    wxDialog( wxWindow* parent, wxWindowID id = SYMBOL_WXDIALOG_IDNAME, const wxString& caption = SYMBOL_WXDIALOG_TITLE, const wxPoint& pos = SYMBOL_WXDIALOG_POSITION, const wxSize& size = SYMBOL_WXDIALOG_SIZE, long style = SYMBOL_WXDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXDIALOG_IDNAME, const wxString& caption = SYMBOL_WXDIALOG_TITLE, const wxPoint& pos = SYMBOL_WXDIALOG_POSITION, const wxSize& size = SYMBOL_WXDIALOG_SIZE, long style = SYMBOL_WXDIALOG_STYLE );

    /// Destructor
    ~wxDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxDialog event handler declarations

////@end wxDialog event handler declarations

////@begin wxDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxDialog member variables
////@end wxDialog member variables
};

#endif
    // _NEWPROJECT_H_
