/////////////////////////////////////////////////////////////////////////////
// Name:        querieseditor.cpp
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Tue 21 Aug 12:23:05 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Tue 21 Aug 12:23:05 2007

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "querieseditor.h"

////@begin XPM images
////@end XPM images


/*!
 * QueriesEditor type definition
 */

IMPLEMENT_DYNAMIC_CLASS( QueriesEditor, wxDialog )


/*!
 * QueriesEditor event table definition
 */

BEGIN_EVENT_TABLE( QueriesEditor, wxDialog )

////@begin QueriesEditor event table entries
////@end QueriesEditor event table entries

END_EVENT_TABLE()


/*!
 * QueriesEditor constructors
 */

QueriesEditor::QueriesEditor()
{
    Init();
}

QueriesEditor::QueriesEditor( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}


/*!
 * QueriesEditor creator
 */

bool QueriesEditor::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin QueriesEditor creation
    SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end QueriesEditor creation
    return true;
}


/*!
 * QueriesEditor destructor
 */

QueriesEditor::~QueriesEditor()
{
////@begin QueriesEditor destruction
////@end QueriesEditor destruction
}


/*!
 * Member initialisation
 */

void QueriesEditor::Init()
{
////@begin QueriesEditor member initialisation
////@end QueriesEditor member initialisation
}


/*!
 * Control creation for QueriesEditor
 */

void QueriesEditor::CreateControls()
{    
////@begin QueriesEditor content construction
    // Generated by DialogBlocks, Mon 12 Nov 13:48:46 2007 (Personal Edition)

    QueriesEditor* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    wxStaticBox* itemStaticBoxSizer3Static = new wxStaticBox(itemDialog1, wxID_ANY, _("Define your queries"));
    wxStaticBoxSizer* itemStaticBoxSizer3 = new wxStaticBoxSizer(itemStaticBoxSizer3Static, wxVERTICAL);
    itemBoxSizer2->Add(itemStaticBoxSizer3, 1, wxGROW|wxALL, 5);

    wxListCtrl* itemListCtrl4 = new wxListCtrl( itemDialog1, ID_LISTCTRL4, wxDefaultPosition, wxSize(100, 100), wxLC_REPORT );
    itemStaticBoxSizer3->Add(itemListCtrl4, 1, wxGROW|wxTOP|wxBOTTOM, 5);

    wxBoxSizer* itemBoxSizer5 = new wxBoxSizer(wxHORIZONTAL);
    itemStaticBoxSizer3->Add(itemBoxSizer5, 0, wxALIGN_LEFT|wxLEFT|wxRIGHT, 5);

    wxToggleButton* itemToggleButton6 = new wxToggleButton( itemDialog1, ID_TOGGLEBUTTON13, _("+"), wxDefaultPosition, wxSize(40, -1), 0 );
    itemToggleButton6->SetValue(false);
    itemBoxSizer5->Add(itemToggleButton6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxToggleButton* itemToggleButton7 = new wxToggleButton( itemDialog1, ID_TOGGLEBUTTON14, _("-"), wxDefaultPosition, wxSize(40, -1), 0 );
    itemToggleButton7->SetValue(false);
    itemBoxSizer5->Add(itemToggleButton7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxToggleButton* itemToggleButton8 = new wxToggleButton( itemDialog1, ID_TOGGLEBUTTON15, _("Run selected"), wxDefaultPosition, wxDefaultSize, 0 );
    itemToggleButton8->SetValue(false);
    itemBoxSizer5->Add(itemToggleButton8, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxBoxSizer* itemBoxSizer9 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer9, 0, wxALIGN_RIGHT|wxALL, 5);

    wxButton* itemButton10 = new wxButton( itemDialog1, ID_BUTTON, _("Clear selection"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer9->Add(itemButton10, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton11 = new wxButton( itemDialog1, wxID_CLOSE, _("&Close"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer9->Add(itemButton11, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton12 = new wxButton( itemDialog1, wxID_SAVE, _("&Save queries"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer9->Add(itemButton12, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStatusBar* itemStatusBar13 = new wxStatusBar( itemDialog1, ID_STATUSBAR1, wxST_SIZEGRIP|wxNO_BORDER );
    itemStatusBar13->SetFieldsCount(2);
    itemStatusBar13->SetStatusText(_("Query passed OK"), 0);
    itemStatusBar13->SetStatusText(_("10 Queries"), 1);
    int itemStatusBar13Widths[2];
    itemStatusBar13Widths[0] = -2;
    itemStatusBar13Widths[1] = -1;
    itemStatusBar13->SetStatusWidths(2, itemStatusBar13Widths);
    itemBoxSizer2->Add(itemStatusBar13, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

////@end QueriesEditor content construction
}


/*!
 * Should we show tooltips?
 */

bool QueriesEditor::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap QueriesEditor::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin QueriesEditor bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end QueriesEditor bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon QueriesEditor::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin QueriesEditor icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end QueriesEditor icon retrieval
}
