/////////////////////////////////////////////////////////////////////////////
// Name:        querieseditor.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Tue 21 Aug 12:23:05 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Tue 21 Aug 12:23:05 2007

#ifndef _QUERIESEDITOR_H_
#define _QUERIESEDITOR_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/listctrl.h"
#include "wx/tglbtn.h"
#include "wx/statusbr.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_QUERIESEDITOR 10049
#define ID_LISTCTRL4 10051
#define ID_TOGGLEBUTTON13 10052
#define ID_TOGGLEBUTTON14 10064
#define ID_TOGGLEBUTTON15 10236
#define ID_BUTTON 10000
#define ID_STATUSBAR1 10065
#define SYMBOL_QUERIESEDITOR_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_QUERIESEDITOR_TITLE _("Queries Editor")
#define SYMBOL_QUERIESEDITOR_IDNAME ID_QUERIESEDITOR
#define SYMBOL_QUERIESEDITOR_SIZE wxSize(400, 300)
#define SYMBOL_QUERIESEDITOR_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * QueriesEditor class declaration
 */

class QueriesEditor: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( QueriesEditor )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    QueriesEditor();
    QueriesEditor( wxWindow* parent, wxWindowID id = SYMBOL_QUERIESEDITOR_IDNAME, const wxString& caption = SYMBOL_QUERIESEDITOR_TITLE, const wxPoint& pos = SYMBOL_QUERIESEDITOR_POSITION, const wxSize& size = SYMBOL_QUERIESEDITOR_SIZE, long style = SYMBOL_QUERIESEDITOR_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_QUERIESEDITOR_IDNAME, const wxString& caption = SYMBOL_QUERIESEDITOR_TITLE, const wxPoint& pos = SYMBOL_QUERIESEDITOR_POSITION, const wxSize& size = SYMBOL_QUERIESEDITOR_SIZE, long style = SYMBOL_QUERIESEDITOR_STYLE );

    /// Destructor
    ~QueriesEditor();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin QueriesEditor event handler declarations

////@end QueriesEditor event handler declarations

////@begin QueriesEditor member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end QueriesEditor member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin QueriesEditor member variables
////@end QueriesEditor member variables
};

#endif
    // _QUERIESEDITOR_H_
