/////////////////////////////////////////////////////////////////////////////
// Name:        rastersymbology.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Tue  9 Oct 08:35:05 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Tue 9 Oct 08:35:05 2007

#ifndef _RASTERSYMBOLOGY_H_
#define _RASTERSYMBOLOGY_H_

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_RASTERSYMBOLOGY 10221
#define ID_SLIDER2 10222
#define ID_TEXTCTRL20 10223
#define ID_BUTTON34 10224
#define SYMBOL_RASTERSYMBOLOGY_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_RASTERSYMBOLOGY_TITLE _("Raster symbology")
#define SYMBOL_RASTERSYMBOLOGY_IDNAME ID_RASTERSYMBOLOGY
#define SYMBOL_RASTERSYMBOLOGY_SIZE wxSize(400, 300)
#define SYMBOL_RASTERSYMBOLOGY_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * Rastersymbology class declaration
 */

class Rastersymbology: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( Rastersymbology )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    Rastersymbology();
    Rastersymbology( wxWindow* parent, wxWindowID id = SYMBOL_RASTERSYMBOLOGY_IDNAME, const wxString& caption = SYMBOL_RASTERSYMBOLOGY_TITLE, const wxPoint& pos = SYMBOL_RASTERSYMBOLOGY_POSITION, const wxSize& size = SYMBOL_RASTERSYMBOLOGY_SIZE, long style = SYMBOL_RASTERSYMBOLOGY_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_RASTERSYMBOLOGY_IDNAME, const wxString& caption = SYMBOL_RASTERSYMBOLOGY_TITLE, const wxPoint& pos = SYMBOL_RASTERSYMBOLOGY_POSITION, const wxSize& size = SYMBOL_RASTERSYMBOLOGY_SIZE, long style = SYMBOL_RASTERSYMBOLOGY_STYLE );

    /// Destructor
    ~Rastersymbology();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin Rastersymbology event handler declarations

////@end Rastersymbology event handler declarations

////@begin Rastersymbology member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end Rastersymbology member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin Rastersymbology member variables
////@end Rastersymbology member variables
};

#endif
    // _RASTERSYMBOLOGY_H_
