/////////////////////////////////////////////////////////////////////////////
// Name:        selectadvancedshortcutvalues.cpp
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Fri 28 Sep 14:54:04 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Fri 28 Sep 14:54:04 2007

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "selectadvancedshortcutvalues.h"

////@begin XPM images
////@end XPM images


/*!
 * Selectadvancedshortcutvalues type definition
 */

IMPLEMENT_DYNAMIC_CLASS( Selectadvancedshortcutvalues, wxDialog )


/*!
 * Selectadvancedshortcutvalues event table definition
 */

BEGIN_EVENT_TABLE( Selectadvancedshortcutvalues, wxDialog )

////@begin Selectadvancedshortcutvalues event table entries
////@end Selectadvancedshortcutvalues event table entries

END_EVENT_TABLE()


/*!
 * Selectadvancedshortcutvalues constructors
 */

Selectadvancedshortcutvalues::Selectadvancedshortcutvalues()
{
    Init();
}

Selectadvancedshortcutvalues::Selectadvancedshortcutvalues( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}


/*!
 * Selectadvancedshortcutvalues creator
 */

bool Selectadvancedshortcutvalues::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin Selectadvancedshortcutvalues creation
    SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end Selectadvancedshortcutvalues creation
    return true;
}


/*!
 * Selectadvancedshortcutvalues destructor
 */

Selectadvancedshortcutvalues::~Selectadvancedshortcutvalues()
{
////@begin Selectadvancedshortcutvalues destruction
////@end Selectadvancedshortcutvalues destruction
}


/*!
 * Member initialisation
 */

void Selectadvancedshortcutvalues::Init()
{
////@begin Selectadvancedshortcutvalues member initialisation
////@end Selectadvancedshortcutvalues member initialisation
}


/*!
 * Control creation for Selectadvancedshortcutvalues
 */

void Selectadvancedshortcutvalues::CreateControls()
{    
////@begin Selectadvancedshortcutvalues content construction
    // Generated by DialogBlocks, Mon 12 Nov 13:58:39 2007 (Personal Edition)

    Selectadvancedshortcutvalues* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    wxArrayString itemListBox3Strings;
    wxListBox* itemListBox3 = new wxListBox( itemDialog1, ID_LISTBOX5, wxDefaultPosition, wxSize(200, 200), itemListBox3Strings, wxLB_SINGLE );
    itemBoxSizer2->Add(itemListBox3, 1, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer4, 0, wxALIGN_RIGHT|wxALL, 5);

    wxButton* itemButton5 = new wxButton( itemDialog1, ID_BUTTON31, _("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton6 = new wxButton( itemDialog1, ID_BUTTON32, _("Save"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

////@end Selectadvancedshortcutvalues content construction
}


/*!
 * Should we show tooltips?
 */

bool Selectadvancedshortcutvalues::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap Selectadvancedshortcutvalues::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin Selectadvancedshortcutvalues bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end Selectadvancedshortcutvalues bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon Selectadvancedshortcutvalues::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin Selectadvancedshortcutvalues icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end Selectadvancedshortcutvalues icon retrieval
}
