/////////////////////////////////////////////////////////////////////////////
// Name:        snapping.cpp
// Purpose:
// Author:      Lucien Schreiber
// Modified by:
// Created:     Fri 31 Aug 11:12:00 2007
// RCS-ID:
// Copyright:   (c) CREALP 2007
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Fri 31 Aug 11:12:00 2007

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "snapping.h"

////@begin XPM images
////@end XPM images

/*!
 * Snapping type definition
 */

IMPLEMENT_DYNAMIC_CLASS(Snapping, wxDialog)

/*!
 * Snapping event table definition
 */

BEGIN_EVENT_TABLE(Snapping, wxDialog)

////@begin Snapping event table entries
////@end Snapping event table entries

END_EVENT_TABLE()

/*!
 * Snapping constructors
 */

Snapping::Snapping() {
  Init();
}

Snapping::Snapping(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size,
                   long style) {
  Init();
  Create(parent, id, caption, pos, size, style);
}

/*!
 * Snapping creator
 */

bool Snapping::Create(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size,
                      long style) {
  ////@begin Snapping creation
  SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
  wxDialog::Create(parent, id, caption, pos, size, style);

  CreateControls();
  if (GetSizer()) {
    GetSizer()->SetSizeHints(this);
  }
  Centre();
  ////@end Snapping creation
  return true;
}

/*!
 * Snapping destructor
 */

Snapping::~Snapping() {
  ////@begin Snapping destruction
  ////@end Snapping destruction
}

/*!
 * Member initialisation
 */

void Snapping::Init() {
  ////@begin Snapping member initialisation
  ////@end Snapping member initialisation
}

/*!
 * Control creation for Snapping
 */

void Snapping::CreateControls() {
  ////@begin Snapping content construction
  // Generated by DialogBlocks, Thu 18 Oct 10:51:08 2007 (Personal Edition)

  Snapping* itemDialog1 = this;

  wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
  itemDialog1->SetSizer(itemBoxSizer2);

  wxStaticBox* itemStaticBoxSizer3Static = new wxStaticBox(itemDialog1, wxID_ANY, _("Snapping properties"));
  wxStaticBoxSizer* itemStaticBoxSizer3 = new wxStaticBoxSizer(itemStaticBoxSizer3Static, wxVERTICAL);
  itemBoxSizer2->Add(itemStaticBoxSizer3, 1, wxGROW | wxALL, 5);

  wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
  itemStaticBoxSizer3->Add(itemBoxSizer4, 0, wxGROW | wxALL, 5);

  wxStaticText* itemStaticText5 = new wxStaticText(itemDialog1, wxID_STATIC, _("Snapping tolerance (map unit) :"),
                                                   wxDefaultPosition, wxDefaultSize, 0);
  itemBoxSizer4->Add(itemStaticText5, 0, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxSpinCtrl* itemSpinCtrl6 =
      new wxSpinCtrl(itemDialog1, ID_SPINCTRL1, _T("0"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 1000, 0);
  itemBoxSizer4->Add(itemSpinCtrl6, 1, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxArrayString itemCheckListBox7Strings;
  wxCheckListBox* itemCheckListBox7 = new wxCheckListBox(itemDialog1, ID_CHECKLISTBOX1, wxDefaultPosition,
                                                         wxDefaultSize, itemCheckListBox7Strings, wxLB_SINGLE);
  itemStaticBoxSizer3->Add(itemCheckListBox7, 1, wxGROW | wxALL, 5);

  wxBoxSizer* itemBoxSizer8 = new wxBoxSizer(wxHORIZONTAL);
  itemStaticBoxSizer3->Add(itemBoxSizer8, 0, wxGROW | wxALL, 5);

  wxToggleButton* itemToggleButton9 =
      new wxToggleButton(itemDialog1, ID_TOGGLEBUTTON21, _("+"), wxDefaultPosition, wxSize(40, -1), 0);
  itemToggleButton9->SetValue(false);
  itemBoxSizer8->Add(itemToggleButton9, 0, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxToggleButton* itemToggleButton10 =
      new wxToggleButton(itemDialog1, ID_TOGGLEBUTTON22, _("-"), wxDefaultPosition, wxSize(40, -1), 0);
  itemToggleButton10->SetValue(false);
  itemBoxSizer8->Add(itemToggleButton10, 0, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxToggleButton* itemToggleButton11 =
      new wxToggleButton(itemDialog1, ID_TOGGLEBUTTON25, _("Clear"), wxDefaultPosition, wxDefaultSize, 0);
  itemToggleButton11->SetValue(false);
  itemBoxSizer8->Add(itemToggleButton11, 0, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxStdDialogButtonSizer* itemStdDialogButtonSizer12 = new wxStdDialogButtonSizer;

  itemBoxSizer2->Add(itemStdDialogButtonSizer12, 0, wxALIGN_RIGHT | wxALL, 5);
  wxButton* itemButton13 = new wxButton(itemDialog1, wxID_OK, _("&Save"), wxDefaultPosition, wxDefaultSize, 0);
  itemStdDialogButtonSizer12->AddButton(itemButton13);

  wxButton* itemButton14 = new wxButton(itemDialog1, wxID_CANCEL, _("&Cancel"), wxDefaultPosition, wxDefaultSize, 0);
  itemStdDialogButtonSizer12->AddButton(itemButton14);

  itemStdDialogButtonSizer12->Realize();

  ////@end Snapping content construction
}

/*!
 * Should we show tooltips?
 */

bool Snapping::ShowToolTips() {
  return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap Snapping::GetBitmapResource(const wxString& name) {
  // Bitmap retrieval
  ////@begin Snapping bitmap retrieval
  wxUnusedVar(name);
  return wxNullBitmap;
  ////@end Snapping bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon Snapping::GetIconResource(const wxString& name) {
  // Icon retrieval
  ////@begin Snapping icon retrieval
  wxUnusedVar(name);
  return wxNullIcon;
  ////@end Snapping icon retrieval
}
