/////////////////////////////////////////////////////////////////////////////
// Name:        tocwindow_dlg.cpp
// Purpose:
// Author:      Lucien Schreiber
// Modified by:
// Created:     Mon  3 Dec 18:27:07 2007
// RCS-ID:
// Copyright:   (c) CREALP 2007
// Licence:
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 3 Dec 18:27:07 2007

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "tocwindow_dlg.h"

////@begin XPM images
////@end XPM images

/*!
 * tocwindow_dlg type definition
 */

IMPLEMENT_DYNAMIC_CLASS(tocwindow_dlg, wxDialog)

/*!
 * tocwindow_dlg event table definition
 */

BEGIN_EVENT_TABLE(tocwindow_dlg, wxDialog)

////@begin tocwindow_dlg event table entries
////@end tocwindow_dlg event table entries

END_EVENT_TABLE()

/*!
 * tocwindow_dlg constructors
 */

tocwindow_dlg::tocwindow_dlg() {
  Init();
}

tocwindow_dlg::tocwindow_dlg(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos,
                             const wxSize& size, long style) {
  Init();
  Create(parent, id, caption, pos, size, style);
}

/*!
 * tocwindow_dlg creator
 */

bool tocwindow_dlg::Create(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos,
                           const wxSize& size, long style) {
  ////@begin tocwindow_dlg creation
  SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
  wxDialog::Create(parent, id, caption, pos, size, style);

  CreateControls();
  if (GetSizer()) {
    GetSizer()->SetSizeHints(this);
  }
  Centre();
  ////@end tocwindow_dlg creation
  return true;
}

/*!
 * tocwindow_dlg destructor
 */

tocwindow_dlg::~tocwindow_dlg() {
  ////@begin tocwindow_dlg destruction
  ////@end tocwindow_dlg destruction
}

/*!
 * Member initialisation
 */

void tocwindow_dlg::Init() {
  ////@begin tocwindow_dlg member initialisation
  ////@end tocwindow_dlg member initialisation
}

/*!
 * Control creation for tocwindow_dlg
 */

void tocwindow_dlg::CreateControls() {
  ////@begin tocwindow_dlg content construction
  // Generated by DialogBlocks, Mon 3 Dec 19:03:46 2007 (Personal Edition)

  tocwindow_dlg* itemDialog1 = this;

  wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
  itemDialog1->SetSizer(itemBoxSizer2);

  wxTreeCtrl* itemTreeCtrl3 =
      new wxTreeCtrl(itemDialog1, ID_TREECTRL1, wxDefaultPosition, wxSize(100, 300), wxTR_SINGLE);
  itemBoxSizer2->Add(itemTreeCtrl3, 1, wxGROW | wxALL, 5);

  wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
  itemBoxSizer2->Add(itemBoxSizer4, 0, wxALIGN_LEFT | wxALL, 5);

  wxToggleButton* itemToggleButton5 =
      new wxToggleButton(itemDialog1, ID_DLGTOC_ADD, _("+"), wxDefaultPosition, wxSize(40, -1), 0);
  itemToggleButton5->SetValue(false);
  itemBoxSizer4->Add(itemToggleButton5, 0, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  wxToggleButton* itemToggleButton6 =
      new wxToggleButton(itemDialog1, ID_DLGTOC_REMOVE, _("-"), wxDefaultPosition, wxSize(40, -1), 0);
  itemToggleButton6->SetValue(false);
  itemBoxSizer4->Add(itemToggleButton6, 0, wxALIGN_CENTER_VERTICAL | wxALL, 5);

  ////@end tocwindow_dlg content construction
}

/*!
 * Should we show tooltips?
 */

bool tocwindow_dlg::ShowToolTips() {
  return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap tocwindow_dlg::GetBitmapResource(const wxString& name) {
  // Bitmap retrieval
  ////@begin tocwindow_dlg bitmap retrieval
  wxUnusedVar(name);
  return wxNullBitmap;
  ////@end tocwindow_dlg bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon tocwindow_dlg::GetIconResource(const wxString& name) {
  // Icon retrieval
  ////@begin tocwindow_dlg icon retrieval
  wxUnusedVar(name);
  return wxNullIcon;
  ////@end tocwindow_dlg icon retrieval
}
