/////////////////////////////////////////////////////////////////////////////
// Name:        zoomtocoordinate.h
// Purpose:     
// Author:      Lucien Schreiber
// Modified by: 
// Created:     Mon 22 Oct 11:30:06 2007
// RCS-ID:      
// Copyright:   (c) CREALP 2007
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Mon 22 Oct 11:30:06 2007

#ifndef _ZOOMTOCOORDINATE_H_
#define _ZOOMTOCOORDINATE_H_

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ZOOMTOCOORDINATE 10243
#define ID_TEXTCTRL22 10244
#define ID_TEXTCTRL23 10245
#define ID_LISTBOX7 10246
#define ID_TEXTCTRL24 10247
#define ID_BUTTON3 10248
#define SYMBOL_ZOOMTOCOORDINATE_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_ZOOMTOCOORDINATE_TITLE _("Zoom to coordinate")
#define SYMBOL_ZOOMTOCOORDINATE_IDNAME ID_ZOOMTOCOORDINATE
#define SYMBOL_ZOOMTOCOORDINATE_SIZE wxSize(400, 300)
#define SYMBOL_ZOOMTOCOORDINATE_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * Zoomtocoordinate class declaration
 */

class Zoomtocoordinate: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( Zoomtocoordinate )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    Zoomtocoordinate();
    Zoomtocoordinate( wxWindow* parent, wxWindowID id = SYMBOL_ZOOMTOCOORDINATE_IDNAME, const wxString& caption = SYMBOL_ZOOMTOCOORDINATE_TITLE, const wxPoint& pos = SYMBOL_ZOOMTOCOORDINATE_POSITION, const wxSize& size = SYMBOL_ZOOMTOCOORDINATE_SIZE, long style = SYMBOL_ZOOMTOCOORDINATE_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ZOOMTOCOORDINATE_IDNAME, const wxString& caption = SYMBOL_ZOOMTOCOORDINATE_TITLE, const wxPoint& pos = SYMBOL_ZOOMTOCOORDINATE_POSITION, const wxSize& size = SYMBOL_ZOOMTOCOORDINATE_SIZE, long style = SYMBOL_ZOOMTOCOORDINATE_STYLE );

    /// Destructor
    ~Zoomtocoordinate();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin Zoomtocoordinate event handler declarations

////@end Zoomtocoordinate event handler declarations

////@begin Zoomtocoordinate member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end Zoomtocoordinate member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin Zoomtocoordinate member variables
////@end Zoomtocoordinate member variables
};

#endif
    // _ZOOMTOCOORDINATE_H_
