/* Autogenerated by png2wx.pl on Mon Jan 31 14:56:16 2011 */
#ifndef _BACKUP_BMP_
#define _BACKUP_BMP_ 1

#include <wx/wxprec.h>

#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

extern void images_backup_init(void);

extern void images_backup_clean(void);

extern wxBitmap *_img_backup_tm;
extern wxBitmap *_img_backup_zip;

#endif /* _BACKUP_BMP_ */
