/* Autogenerated by png2wx.pl on Thu Feb 10 14:19:31 2011 */
#ifndef _CURSOR_BMP_H_
#define _CURSOR_BMP_H_ 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void images_cursor_init(void);
extern void images_cursor_clean(void);


extern wxBitmap *_img_cursor_editing;
extern wxBitmap *_img_cursor_hand;
extern wxBitmap *_img_cursor_oriented;
extern wxBitmap *_img_cursor_zoom_in;
extern wxBitmap *_img_cursor_zoom_out;
extern wxBitmap *_img_cursor_add;
extern wxBitmap *_img_cursor_close;

#endif /* _CURSOR_BMP_H_ */
