/* Autogenerated by png2wx.pl on Tue Jan 14 10:22:20 2020 */
#ifndef _MISC_BMP_H_
#define _MISC_BMP_H_ 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

#ifdef _MSC_VER
#pragma warning( disable : 4125 ) // C4125: decimal digit terminates octal escape sequence
#endif

extern void images_misc_init();
extern void images_misc_clean();

extern wxBitmap *_img_icon_bug;
extern wxBitmap *_img_icon_toolmap;
extern wxBitmap *_img_icon_toolmap_about;

#endif /* _MISC_BMP_H_ */
