/* Autogenerated by png2wx.pl on Thu Feb 10 14:21:15 2011 */
#ifndef _MISC_BMP_H_
#define _MISC_BMP_H_ 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void images_misc_init(void);
extern void images_misc_clean(void);

extern wxBitmap *_img_btn_option;
extern wxBitmap *_img_icon_bug;
extern wxBitmap *_img_icon_toolmap;
extern wxBitmap *_img_icon_toolmap_about;


#endif /* _MISC_BMP_H_ */
