/* Autogenerated by png2wx.pl on Thu Feb 10 14:18:28 2011 */
#ifndef _TOOLBAR_BMP_H_
#define _TOOLBAR_BMP_H_ 1

#include <wx/wxprec.h>

#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void images_toolbar_init(void);

extern void images_toolbar_clean(void);

extern wxBitmap *_img_toolbar_attribute;
// extern wxBitmap *_img_toolbar_attribute_copy;
extern wxBitmap *_img_toolbar_attribute_extend;
extern wxBitmap *_img_toolbar_edit;
extern wxBitmap *_img_toolbar_info;
extern wxBitmap *_img_toolbar_modify;
extern wxBitmap *_img_toolbar_pan;
extern wxBitmap *_img_toolbar_previous;
extern wxBitmap *_img_toolbar_select;
extern wxBitmap *_img_toolbar_vertex_move;
extern wxBitmap *_img_toolbar_zoom;
extern wxBitmap *_img_toolbar_zoom_fit;

#endif /* _TOOLBAR_BMP_H_ */
