name: Doxygen generation

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build-doxygen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build the HTML documentation
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.12.0
        with:
          doxyfile-path: ./Doxyfile
          working-directory: ./doc

      # Deploy the HTML documentation to GitHub Pages
      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: terranum-ch/ToolMap-dev-doc
          publish_dir: ./doc/html/
          destination_dir: doxygen
          enable_jekyll: true
          allow_empty_commit: false
          force_orphan: false
          publish_branch: main
