name: Tests-Windows

on: [ push ]

jobs:
  build:
    name: Windows testing
    
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install conan
        conan config set general.revisions_enabled=1
        
        # gitlab support (wxwidgets, mysql, gdal)
        conan remote add gitlab https://gitlab.com/api/v4/packages/conan

    - name: Install libraries
      run: |
        mkdir ${{github.workspace}}/bin
        cd ${{github.workspace}}/bin
        conan install .. -o unit_test=True

    - name: Build
      working-directory: ${{github.workspace}}/bin
      run: conan build ..

    - name: List directory content
      working-directory: ${{github.workspace}}
      run: tree .

    - name: Run tests
      working-directory: ${{github.workspace}}/bin
      run: bin/UnitTests
