name: Tests-Windows

on: [ push ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    name: Windows testing
    
    runs-on: windows-2022

    env:
      PROJ_LIB: ${{github.workspace}}/bin/bin

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install wheel conan
        
        # gitlab support (wxwidgets, mysql, gdal)
        conan remote add gitlab https://gitlab.com/api/v4/packages/conan
        
        # create default profile with libstdc++11
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Install libraries
      run: |
        mkdir ${{github.workspace}}/bin
        cd ${{github.workspace}}/bin
        conan install .. -o unit_test=True

    - name: Build
      working-directory: ${{github.workspace}}/bin
      run: conan build ..

    - name: List directory content
      working-directory: ${{github.workspace}}
      run: tree .

    - name: Run tests
      working-directory: ${{github.workspace}}/bin
      run: bin/UnitTests
