name: Windows build

on: [ push ]

jobs:
  test:
    name: Windows testing
    
    runs-on: windows-2019

    env:
      BUILD_TYPE: RelWithDebInfo
      PROJ_LIB: ${{github.workspace}}/bin/share/proj

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install conan
      run: |
        python -m pip install --upgrade pip
        pip install conan

        # gitlab support
        conan config set general.revisions_enabled=1
        conan remote add gitlab https://gitlab.com/api/v4/packages/conan
        conan user gitlab+deploy-token-653038 -r gitlab -p sBwmejFz5Pn-gZPSNFMy

    - name: Install libraries
      run: |
        mkdir ${{github.workspace}}/bin
        cd ${{github.workspace}}/bin
        conan install .. -o unit_test=True --build=libtiff

    - name: Configure
      working-directory: ${{github.workspace}}/bin
      run: cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_UNITTEST=1

    - name: Build
      working-directory: ${{github.workspace}}/bin
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Run tests
      working-directory: ${{github.workspace}}/bin/bin
      run: .\UnitTests

    - name: CPack
      working-directory: ${{github.workspace}}/bin
      run: |
        cpack -C ${{env.BUILD_TYPE}} -G ZIP
        cpack -C ${{env.BUILD_TYPE}} -G WIX
